export const v0Template = {
	node_id: "MAGIC-FLOW-NODE-6649c0573a3686-33859327",
	name: "代码执行",
	description: "",
	node_type: 5,
	meta: [],
	params: {
		language: "php",
		mode: "normal",
		code: "<?php\n// Example: Convert the string-type input to an array-type output\n// Tutorials: https://www.w3schools.com/php/\n\n$output = explode(',', $input);\n\nreturn [\n    'output' => $output\n];",
		import_code: {
			id: "component-67ad532215e7e",
			version: "1",
			type: "value",
			structure: {
				type: "const",
				const_value: [
					{
						type: "input",
						value: "",
						name: "",
						args: null,
					},
				],
				expression_value: null,
			},
		},
	},
	next_nodes: [],
	input: {
		widget: null,
		form: {
			id: "component-6649c0573a37b",
			version: "1",
			type: "form",
			structure: {
				key: "root",
				sort: 0,
				type: "object",
				items: null,
				title: null,
				value: null,
				required: ["input"],
				encryption: false,
				properties: {
					input: {
						key: "arguments_str",
						sort: 0,
						type: "string",
						items: null,
						title: "",
						required: null,
						encryption: false,
						properties: null,
						description: "",
						encryption_value: null,
						value: {
							type: "const",
							const_value: [
								{
									type: "input",
									uniqueId: "671627623276744705",
									value: "hello,magic",
								},
							],
							expression_value: [],
						},
					},
				},
				description: null,
				encryption_value: null,
			},
		},
	},
	output: {
		widget: null,
		form: {
			id: "component-6649c0573a38e",
			version: "1",
			type: "form",
			structure: {
				key: "root",
				sort: 0,
				type: "object",
				items: null,
				title: "",
				value: null,
				required: ["output"],
				encryption: false,
				properties: {
					output: {
						key: "arguments_array",
						sort: 0,
						type: "array",
						items: {
							key: "",
							sort: 0,
							type: "string",
							items: null,
							title: "",
							value: null,
							required: null,
							encryption: false,
							properties: null,
							description: "",
							encryption_value: null,
						},
						title: "",
						value: null,
						required: null,
						encryption: false,
						properties: null,
						description: "",
						encryption_value: null,
					},
				},
				description: "",
				encryption_value: null,
			},
		},
	},
}
