export const v1Template = {
	node_id: "MAGIC-FLOW-NODE-677d3b00a34c56-01323640",
	debug: false,
	name: "开始",
	description: "",
	node_type: 1,
	node_version: "v1",
	meta: [],
	params: {
		branches: [
			{
				branch_id: "branch_677d3b00a34de",
				trigger_type: 1,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-677d3b00a3521",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root节点",
							description: "",
							required: [
								"conversation_id",
								"topic_id",
								"message_content",
								"message_type",
								"message_time",
								"organization_code",
								"user",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 0,
									title: "会话 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 1,
									title: "话题 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_content: {
									type: "string",
									key: "message_content",
									sort: 2,
									title: "消息内容",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_type: {
									type: "string",
									key: "message_type",
									sort: 3,
									title: "消息类型",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_time: {
									type: "string",
									key: "message_time",
									sort: 4,
									title: "发送时间",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 5,
									title: "组织编码",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								files: {
									type: "array",
									key: "files",
									sort: 6,
									title: "文件列表",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: {
										type: "object",
										key: "files",
										sort: 0,
										title: "文件",
										description: "",
										required: ["name", "url", "extension", "size"],
										value: null,
										encryption: false,
										encryption_value: null,
										items: null,
										properties: {
											name: {
												type: "string",
												key: "name",
												sort: 0,
												title: "文件名称",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											url: {
												type: "string",
												key: "url",
												sort: 1,
												title: "文件链接",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											extension: {
												type: "string",
												key: "extension",
												sort: 2,
												title: "文件扩展名",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											size: {
												type: "number",
												key: "size",
												sort: 3,
												title: "文件大小",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
										},
									},
									properties: null,
								},
								user: {
									type: "object",
									key: "user",
									sort: 7,
									title: "用户",
									description: "",
									required: [
										"id",
										"nickname",
										"real_name",
										"position",
										"phone_number",
										"work_number",
									],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										id: {
											type: "string",
											key: "id",
											sort: 0,
											title: "用户 ID",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										nickname: {
											type: "string",
											key: "nickname",
											sort: 1,
											title: "用户昵称",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										real_name: {
											type: "string",
											key: "real_name",
											sort: 2,
											title: "真实姓名",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										position: {
											type: "string",
											key: "position",
											sort: 3,
											title: "岗位",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										work_number: {
											type: "string",
											key: "work_number",
											sort: 4,
											title: "工号",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										departments: {
											type: "array",
											key: "departments",
											sort: 5,
											title: "部门",
											description: "desc",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: {
												type: "object",
												key: "departments",
												sort: 0,
												title: "部门",
												description: "desc",
												required: ["id", "name", "path"],
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: {
													id: {
														type: "string",
														key: "id",
														sort: 0,
														title: "部门 ID",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													name: {
														type: "string",
														key: "name",
														sort: 1,
														title: "部门名称",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													path: {
														type: "string",
														key: "path",
														sort: 2,
														title: "部门路径",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
												},
											},
											properties: null,
										},
									},
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_677d3b00a36ec",
				trigger_type: 2,
				next_nodes: [],
				config: {
					interval: 10,
					unit: "minutes",
				},
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-677d3b00a3710",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root节点",
							description: "",
							required: [
								"conversation_id",
								"topic_id",
								"organization_code",
								"user",
								"open_time",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 0,
									title: "会话 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 1,
									title: "话题 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 2,
									title: "组织编码",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								user: {
									type: "object",
									key: "user",
									sort: 3,
									title: "用户",
									description: "",
									required: ["id", "nickname", "real_name"],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										id: {
											type: "string",
											key: "id",
											sort: 0,
											title: "用户 ID",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										nickname: {
											type: "string",
											key: "nickname",
											sort: 1,
											title: "用户昵称",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										real_name: {
											type: "string",
											key: "real_name",
											sort: 2,
											title: "真实姓名",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										position: {
											type: "string",
											key: "position",
											sort: 3,
											title: "岗位",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										work_number: {
											type: "string",
											key: "work_number",
											sort: 4,
											title: "工号",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										departments: {
											type: "array",
											key: "departments",
											sort: 5,
											title: "部门",
											description: "desc",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: {
												type: "object",
												key: "departments",
												sort: 0,
												title: "部门",
												description: "desc",
												required: ["id", "name", "path"],
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: {
													id: {
														type: "string",
														key: "id",
														sort: 0,
														title: "部门 ID",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													name: {
														type: "string",
														key: "name",
														sort: 1,
														title: "部门名称",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													path: {
														type: "string",
														key: "path",
														sort: 2,
														title: "部门路径",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
												},
											},
											properties: null,
										},
									},
								},
								open_time: {
									type: "string",
									key: "open_time",
									sort: 4,
									title: "打开时间",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_677d3b00a3804",
				trigger_type: 4,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-677d3b00a3807",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				system_output: {
					widget: null,
					form: {
						id: "component-677d3b00a384e",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root节点",
							description: "",
							required: [
								"conversation_id",
								"topic_id",
								"message_content",
								"message_type",
								"message_time",
								"organization_code",
								"user",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 0,
									title: "会话 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 1,
									title: "话题 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_content: {
									type: "string",
									key: "message_content",
									sort: 2,
									title: "消息内容",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_type: {
									type: "string",
									key: "message_type",
									sort: 3,
									title: "消息类型",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_time: {
									type: "string",
									key: "message_time",
									sort: 4,
									title: "发送时间",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 5,
									title: "组织编码",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								files: {
									type: "array",
									key: "files",
									sort: 6,
									title: "文件列表",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: {
										type: "object",
										key: "files",
										sort: 0,
										title: "文件",
										description: "",
										required: ["name", "url", "extension", "size"],
										value: null,
										encryption: false,
										encryption_value: null,
										items: null,
										properties: {
											name: {
												type: "string",
												key: "name",
												sort: 0,
												title: "文件名称",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											url: {
												type: "string",
												key: "url",
												sort: 1,
												title: "文件链接",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											extension: {
												type: "string",
												key: "extension",
												sort: 2,
												title: "文件扩展名",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											size: {
												type: "number",
												key: "size",
												sort: 3,
												title: "文件大小",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
										},
									},
									properties: null,
								},
								user: {
									type: "object",
									key: "user",
									sort: 7,
									title: "用户",
									description: "",
									required: [
										"id",
										"nickname",
										"real_name",
										"position",
										"phone_number",
										"work_number",
									],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										id: {
											type: "string",
											key: "id",
											sort: 0,
											title: "用户 ID",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										nickname: {
											type: "string",
											key: "nickname",
											sort: 1,
											title: "用户昵称",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										real_name: {
											type: "string",
											key: "real_name",
											sort: 2,
											title: "真实姓名",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										position: {
											type: "string",
											key: "position",
											sort: 3,
											title: "岗位",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										work_number: {
											type: "string",
											key: "work_number",
											sort: 4,
											title: "工号",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										departments: {
											type: "array",
											key: "departments",
											sort: 5,
											title: "部门",
											description: "desc",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: {
												type: "object",
												key: "departments",
												sort: 0,
												title: "部门",
												description: "desc",
												required: ["id", "name", "path"],
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: {
													id: {
														type: "string",
														key: "id",
														sort: 0,
														title: "部门 ID",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													name: {
														type: "string",
														key: "name",
														sort: 1,
														title: "部门名称",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													path: {
														type: "string",
														key: "path",
														sort: 2,
														title: "部门路径",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
												},
											},
											properties: null,
										},
									},
								},
							},
						},
					},
				},
				custom_system_output: {
					widget: null,
					form: {
						id: "component-677d3b00a39a0",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
			},
			{
				branch_id: "branch_677d3b00a39be",
				trigger_type: 5,
				next_nodes: [],
				config: null,
				input: null,
				output: null,
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_677d3b00a39c0",
				trigger_type: 7,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-677d3b00a39e0",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root节点",
							description: "",
							required: ["add_time", "user"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								user: {
									type: "object",
									key: "user",
									sort: 0,
									title: "用户",
									description: "",
									required: ["id", "nickname", "real_name"],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										id: {
											type: "string",
											key: "id",
											sort: 0,
											title: "用户 ID",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										nickname: {
											type: "string",
											key: "nickname",
											sort: 1,
											title: "用户昵称",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										real_name: {
											type: "string",
											key: "real_name",
											sort: 2,
											title: "真实姓名",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										position: {
											type: "string",
											key: "position",
											sort: 3,
											title: "岗位",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										work_number: {
											type: "string",
											key: "work_number",
											sort: 4,
											title: "工号",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										departments: {
											type: "array",
											key: "departments",
											sort: 5,
											title: "部门",
											description: "desc",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: {
												type: "object",
												key: "departments",
												sort: 0,
												title: "部门",
												description: "desc",
												required: ["id", "name", "path"],
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: {
													id: {
														type: "string",
														key: "id",
														sort: 0,
														title: "部门 ID",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													name: {
														type: "string",
														key: "name",
														sort: 1,
														title: "部门名称",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
													path: {
														type: "string",
														key: "path",
														sort: 2,
														title: "部门路径",
														description: "",
														required: null,
														value: null,
														encryption: false,
														encryption_value: null,
														items: null,
														properties: null,
													},
												},
											},
											properties: null,
										},
									},
								},
								add_time: {
									type: "string",
									key: "add_time",
									sort: 1,
									title: "添加时间",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
		],
	},
	next_nodes: [],
	input: null,
	output: null,
	system_output: null,
}
