export const v0Template = {
	node_id: "MAGIC-FLOW-NODE-66f3e2032672a3-11827064",
	debug: false,
	name: "接口请求",
	description: "",
	node_type: 10,
	meta: [],
	params: {
		api: {
			id: "component-66f3e20326f16",
			version: "1",
			type: "api",
			structure: {
				method: "GET",
				domain: "",
				path: "",
				uri: null,
				url: "",
				proxy: "",
				auth: "",
				request: {
					params_query: {
						id: "component-66f3e2032705b",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							items: null,
							properties: null,
						},
					},
					params_path: {
						id: "component-66f3e20327543",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							items: null,
							properties: null,
						},
					},
					body_type: "json",
					body: {
						id: "component-66f3e203275c0",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							items: null,
							properties: null,
						},
					},
					headers: {
						id: "component-66f3e203275c5",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							items: null,
							properties: null,
						},
					},
				},
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-66f3e2032767b",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: [],
				value: null,
				items: null,
				properties: null,
			},
		},
	},
	system_output: {
		widget: null,
		form: {
			id: "component-66f3e2032768b",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: ["response_body"],
				value: null,
				items: null,
				properties: {
					response_body: {
						type: "string",
						key: "response_body",
						sort: 0,
						title: "原文输出",
						description: "",
						required: null,
						value: null,
						items: null,
						properties: null,
					},
				},
			},
		},
	},
}
