export const v0Template = {
	node_id: "MAGIC-FLOW-NODE-6735bdc8d72e40-41197531",
	debug: false,
	name: "文本切割",
	description: "",
	node_type: 14,
	meta: [],
	params: {
		strategy: "",
		content: {
			id: "component-6735bdc8d72fb",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: [
					{
						type: "input",
						value: "",
						name: "",
						args: null,
					},
				],
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-6735bdc8d7324",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root节点",
				description: "",
				required: ["split_texts"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					split_texts: {
						type: "array",
						key: "split_texts",
						sort: 0,
						title: "文本片段",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "string",
							key: "0",
							sort: 0,
							title: "文本片段",
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
