export const v0Template = {
	node_id: "MAGIC-FLOW-NODE-675659cd3bde26-74223118",
	debug: false,
	name: "图像生成",
	description: "",
	node_type: 53,
	meta: [],
	params: {
		model: "Midjourney",
		ratio: {
			id: "component-663c6d3ed0aa4",
			version: "1",
			type: "value",
			structure: {
				type: "const",
				expression_value: null,
				const_value: null,
			},
		},
		reference_images: {
			id: "component-663c6d3ed0aar",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				expression_value: null,
				const_value: null,
			},
		},
		height: {
			id: "component-663c6d3ed0aa4",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				expression_value: null,
				const_value: null,
			},
		},
		width: {
			id: "component-663c6d3ed0aa4",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				expression_value: null,
				const_value: null,
			},
		},
		use_sr: false,
		user_prompt: {
			id: "component-663c6d3ed0aa4",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				expression_value: null,
				const_value: null,
			},
		},
		negative_prompt: {
			id: "component-663c6d3ed0aa4",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				expression_value: null,
				const_value: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-675659cd3eb73",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root节点",
				description: "",
				required: ["image_url"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					image_url: {
						type: "string",
						key: "images",
						sort: 0,
						title: "图片链接",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
