import pathlib
replacements = [
    ("test功能钩子","testing hook"),
    ("提供test流式响应和commandProcess的功能","provides testing for streaming responses and command processing"),
    ("追踪当前test会话ID，确保不会有重叠的test","track current test session ID to avoid overlapping tests"),
    ("追踪正在Processcommand的status","track whether commands are being processed"),
    ("强制cleanup所有teststatus","force cleanup of all test states"),
    ("立即reset所有status","reset all states immediately"),
    ("teststatus已reset","test state reset"),
    ("create模拟真实SSE流的ReadableStream，采用更可靠的数据传输方式","create a mock real SSE ReadableStream with more reliable data transfer"),
    ("SSEevent行array","SSE event line array"),
    ("行之间的延迟","delay between lines"),
    ("模拟的SSE流","mock SSE stream"),
    ("确保最小延迟，避免Process不及时","ensure minimum delay to avoid late processing"),
    ("使用更可靠的队列方式Process数据","process data with a more reliable queue"),
    ("加入end检测计数器","add an end-detection counter"),
    ("定义发送下一行的function","define a function to send the next line"),
    ("清除之前的超时","clear previous timeout"),
    ("所有行已发送完毕，关闭流","all lines sent, close stream"),
    ("发送end标记并关闭流","send end marker and close stream"),
    ("SSE流已关闭","SSE stream closed"),
    ("Get当前行并准备下一行","get current line and prepare the next"),
    ("确保每行都有换行符，对于SSEeventProcess至关重要","ensure each line has a newline; critical for SSE events"),
    ("入队并记录日志","enqueue and log"),
    ("安排发送下一行，并Set超时保护","schedule next line and set timeout protection"),
    ("发送SSE行时出错","error sending SSE line"),
    ("出错时也尝试continue发送下一行","on error still try sending next line"),
    ("start发送SSE流, 共","Start sending SSE stream, total"),
    ("行, 延迟"," lines, delay"),
    ("模拟SSE流被Cancel","mock SSE stream cancelled"),
    ("防止进一步发送","prevent further sending"),
    ("test使用真实SSEevent流format","test using real SSE event stream format"),
    ("每行format为 data:{...}","each line formatted as data:{...}"),
    ("如果已经有test在进行中，先强制cleanup","if a test is already running, force cleanup first"),
    ("检测到有未complete的test，先执行强制cleanup","detected unfinished test, performing force cleanup"),
    ("生成新的test会话ID","generate a new test session ID"),
    ("create一个新的AImessageID","create a new AI message ID"),
    ("添加一个空的AImessage，notestatus设为loading","add an empty AI message with status set to loading"),
    ("初始status为loading","initial status is loading"),
    ("start新的SSE流test会话","start new SSE stream test session"),
    ("resetstatus并添加message","reset state and add message"),
    ("清空command队列","clear the command queue"),
    ("create模拟的SSE流","create a mock SSE stream"),
    ("手动listener流Process进度，确保messagestatus正确update","manually monitor stream processing progress to ensure message status updates"),
    ("每秒check一次流Processstatus","check stream processing status every second"),
    ("如果会话ID不匹配或未Process中，Cancelcheck","if session ID mismatches or not processing, cancel the check"),
    ("查找当前message","find the current message"),
    ("checkmessageWhether已有内容但仍处于loadingstatus","check whether the message has content but is still loading"),
    ("updatestatus为done","update status to done"),
    ("如果message有内容但仍是loadingstatus，确保Processcomplete时messagestatus正确","if message has content but is still loading, ensure status correct when processing completes"),
    ("检测到message有内容但status未update，修正status","detected content but status not updated, fixing status"),
    ("60秒后强制cleanup，防止check器无限运行","force cleanup after 60 seconds to avoid infinite checker"),
    ("如果仍在Process中，强制updatemessagestatus并endProcess","if still processing, force update message status and end processing"),
    ("流Process超时，强制complete","stream processing timeout, forcing completion"),
    ("cleanupProcessstatus","clean processing state"),
    ("启动进度check","start progress check"),
    ("Set响应流，让StreamProcessorcomponentProcess","set response stream for StreamProcessor to process"),
    ("以最原始方式从SSEformat数据中提取内容，完全保留所有特殊字符","extract content from SSE data in raw form, preserving special characters"),
    ("SSEformat的完整内容","complete SSE-formatted content"),
    ("提取的原始内容，如果failed则returnnull","extracted raw content, or null on failure"),
    ("按行分割SSE内容","split SSE content by line"),
    ("收集每行的字符内容","collect character content for each line"),
    ("使用forEach代替forloop，避免lintererror","use forEach instead of for loop to avoid linter errors"),
    ("提取data:后的JSON string","extract JSON string after data:"),
    ("尝试多种path提取内容","try multiple paths to extract content"),
    ("常见结构：{\"message\":{\"content\":\"某内容\"}}","common structure: {\"message\":{\"content\":\"...\"}}"),
    ("简单结构：{\"content\":\"某内容\"}","simple structure: {\"content\":\"...\"}"),
    ("纯string结构","pure string structure"),
    ("JSON解析failed，记录日志但continueProcess其他行","JSON parsing failed; log and continue other lines"),
    ("无法解析SSE行JSON数据","unable to parse SSE line JSON data"),
    ("尝试使用正则表达式直接提取content内容","try using regex to extract content directly"),
    ("需要Process转义的双引号和其他特殊字符","need to handle escaped quotes and special characters"),
    ("使用JSON.parse解码转义字符","decode escaped characters using JSON.parse"),
    ("解码failed，直接使用原始匹配内容","decoding failed; use raw matched content"),
    ("如果提取到内容，拼接并return","if content extracted, join and return"),
    ("check特殊字符Whether存在","check whether special characters exist"),
    ("提取内容Contains特殊字符，确保正确Process","extracted content contains special characters; ensure correct handling"),
    ("没有找到内容","no content found"),
    ("从SSE提取内容failed","failed to extract content from SSE"),
    ("直接从原始SSEeventarray中提取纯文本内容，不使用JSON解析","extract plain text directly from raw SSE event array without JSON parsing"),
    ("这个method专门Process一个字符一个event的极端情况","this method handles the extreme case of one character per event"),
    ("SSEeventarray，每个eventformat为data:{\"message\":{\"content\":\"字符\"}}","SSE event array; each event formatted as data:{\"message\":{\"content\":\"char\"}}"),
    ("记录特殊字符匹配情况","log special character matches"),
    ("使用forEach避免lintererror","use forEach to avoid linter errors"),
    ("使用直接string匹配，避免JSON解析error","use direct string matching to avoid JSON parse errors"),
    ("Get引号内的内容并Process转义","get the content inside quotes and handle escapes"),
    ("使用JSON.parseProcess转义字符","use JSON.parse to handle escaped characters"),
    ("check特殊字符","check special characters"),
    ("解析failed时，直接使用原始匹配内容","on parse failure, use raw matched content"),
    ("记录特殊字符情况","log special character situation"),
    ("checkWhether是SSEformat","check whether it is SSE format"),
    ("比较两种method的结果，选择Contains特殊字符更多的那个","compare both methods and choose the one preserving more special characters"),
    ("checkWhether是当前test会话","check whether it is the current test session"),
    ("忽略过时的test会话回调","ignore outdated test session callback"),
    ("checkWhether是当前test会话command","check whether it is the current test session command"),
    ("收到command: ","commands received: "),
    ("没有command需要Process","no commands need processing"),
    ("标记commandProcessstart","mark command processing start"),
    ("如果有command，updatemessage内容指示正在Processcommand","if commands exist, update message content indicating processing commands"),
    ("completeProcess","complete processing"),
    ("忽略过时的test会话command","ignore outdated test session command"),
    ("使用完整响应文本testStreamProcessorcomponent功能","test StreamProcessor with complete response text"),
    ("使用完整的SSEeventstring","test using full SSE event string"),
    ("接收单个Contains多行SSE数据的string","accept a single string containing multiple lines of SSE data"),
    ("自动分割Process","automatically split and process"),
    ("如果内容为空，直接return","if content is empty, return directly"),
    ("内容不是SSEformat，作为原始内容Process","content is not SSE format; process as raw content"),
    ("提取到原始内容，长度: ","extracted raw content, length: "),
    ("使用小块大小确保特殊字符Process正确","use small chunk size to ensure special characters handled correctly"),
    ("messageID","message ID"),
    ("createmock SSE stream","create mock SSE stream"),
    ("获Cancel息最新status","get latest message state"),
    ("updatemessagestatus为done","update message status to done"),
    ("确保是data:开头","ensure it starts with data:"),
    ("使用return代替continue","use return instead of continue"),
    ("尝试解析JSON","try parsing JSON"),
    ("提取的纯文本内容","extracted plain text content"),
    ("避免使用++","avoid using ++"),
    ("checkparameter合法性","validate parameters"),
    ("start新的原始内容test会话","start new raw content test session"),
    ("原始内容长度","raw content length"),
    ("check内容WhetherContains特殊字符","check whether content contains special characters"),
    ("记录特殊字符","log special characters"),
    ("检测到内容Contains特殊字符，使用更小的块大小和精确encoding","detected special characters; use smaller chunk size with precise encoding"),
    ("简单记录特殊字符存在","log that special characters exist"),
    ("发现特殊字符，将使用更严格的Process方式","found special characters; using stricter processing"),
    ("打印含有特殊字符的一小段样本","print a short sample containing special characters"),
    ("特殊字符样本位置: ${i}, 上下文: \"","special character sample at position ${i}, context: \""),
    ("将完整内容分割成小块，每个块都成为一个SSEevent","split the full content into chunks; each chunk becomes an SSE event"),
    ("使用更小的块大小Process特殊字符，确保encoding正确","use smaller chunk size for special characters to ensure correct encoding"),
    ("使用块大小","using chunk size"),
]
path = pathlib.Path(r"frontend/delightful-web/src/opensource/pages/flow/components/FlowAssistant/useTestFunctions.tsx")
text = path.read_text(encoding="utf-8")
for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
print("done")
