import pathlib
replacements = [
    ("测试功能钩子","testing hook"),
    ("提供测试流式响应和命令Process的功能","provides testing for streaming responses and command processing"),
    ("追踪当前测试会话ID，确保不会有重叠的测试","track current test session ID to avoid overlapping tests"),
    ("追踪正在Process命令的状态","track whether commands are being processed"),
    ("强制清理所有测试状态","force cleanup of all test states"),
    ("立即重置所有状态","reset all states immediately"),
    ("测试状态已重置","test state reset"),
    ("创建模拟真实SSE流的ReadableStream，采用更可靠的数据传输方式","create a mock real SSE ReadableStream with more reliable data transfer"),
    ("SSE事件行数组","SSE event line array"),
    ("行之间的延迟","delay between lines"),
    ("模拟的SSE流","mock SSE stream"),
    ("确保最小延迟，避免Process不及时","ensure minimum delay to avoid late processing"),
    ("使用更可靠的队列方式Process数据","process data with a more reliable queue"),
    ("加入结束检测计数器","add an end-detection counter"),
    ("定义发送下一行的函数","define a function to send the next line"),
    ("清除之前的超时","clear previous timeout"),
    ("所有行已发送完毕，关闭流","all lines sent, close stream"),
    ("发送结束标记并关闭流","send end marker and close stream"),
    ("SSE流已关闭","SSE stream closed"),
    ("Get当前行并准备下一行","get current line and prepare the next"),
    ("确保每行都有换行符，对于SSE事件Process至关重要","ensure each line has a newline; critical for SSE events"),
    ("入队并记录日志","enqueue and log"),
    ("安排发送下一行，并Set超时保护","schedule next line and set timeout protection"),
    ("发送SSE行时出错","error sending SSE line"),
    ("出错时也尝试继续发送下一行","on error still try sending next line"),
    ("开始发送SSE流, 共","Start sending SSE stream, total"),
    ("行, 延迟"," lines, delay"),
    ("模拟SSE流被Cancel","mock SSE stream cancelled"),
    ("防止进一步发送","prevent further sending"),
    ("测试使用真实SSE事件流格式","test using real SSE event stream format"),
    ("每行格式为 data:{...}","each line formatted as data:{...}"),
    ("如果已经有测试在进行中，先强制清理","if a test is already running, force cleanup first"),
    ("检测到有未完成的测试，先执行强制清理","detected unfinished test, performing force cleanup"),
    ("生成新的测试会话ID","generate a new test session ID"),
    ("创建一个新的AI消息ID","create a new AI message ID"),
    ("添加一个空的AI消息，注意状态设为loading","add an empty AI message with status set to loading"),
    ("初始状态为loading","initial status is loading"),
    ("开始新的SSE流测试会话","start new SSE stream test session"),
    ("重置状态并添加消息","reset state and add message"),
    ("清空命令队列","clear the command queue"),
    ("创建模拟的SSE流","create a mock SSE stream"),
    ("手动监听流Process进度，确保消息状态正确更新","manually monitor stream processing progress to ensure message status updates"),
    ("每秒检查一次流Process状态","check stream processing status every second"),
    ("如果会话ID不匹配或未Process中，Cancel检查","if session ID mismatches or not processing, cancel the check"),
    ("查找当前消息","find the current message"),
    ("检查消息Whether已有内容但仍处于loading状态","check whether the message has content but is still loading"),
    ("更新状态为done","update status to done"),
    ("如果消息有内容但仍是loading状态，确保Process完成时消息状态正确","if message has content but is still loading, ensure status correct when processing completes"),
    ("检测到消息有内容但状态未更新，修正状态","detected content but status not updated, fixing status"),
    ("60秒后强制清理，防止检查器无限运行","force cleanup after 60 seconds to avoid infinite checker"),
    ("如果仍在Process中，强制更新消息状态并结束Process","if still processing, force update message status and end processing"),
    ("流Process超时，强制完成","stream processing timeout, forcing completion"),
    ("清理Process状态","clean processing state"),
    ("启动进度检查","start progress check"),
    ("Set响应流，让StreamProcessor组件Process","set response stream for StreamProcessor to process"),
    ("以最原始方式从SSE格式数据中提取内容，完全保留所有特殊字符","extract content from SSE data in raw form, preserving special characters"),
    ("SSE格式的完整内容","complete SSE-formatted content"),
    ("提取的原始内容，如果失败则返回null","extracted raw content, or null on failure"),
    ("按行分割SSE内容","split SSE content by line"),
    ("收集每行的字符内容","collect character content for each line"),
    ("使用forEach代替for循环，避免linter错误","use forEach instead of for loop to avoid linter errors"),
    ("提取data:后的JSON string","extract JSON string after data:"),
    ("尝试多种路径提取内容","try multiple paths to extract content"),
    ("常见结构：{\"message\":{\"content\":\"某内容\"}}","common structure: {\"message\":{\"content\":\"...\"}}"),
    ("简单结构：{\"content\":\"某内容\"}","simple structure: {\"content\":\"...\"}"),
    ("纯字符串结构","pure string structure"),
    ("JSON解析失败，记录日志但继续Process其他行","JSON parsing failed; log and continue other lines"),
    ("无法解析SSE行JSON数据","unable to parse SSE line JSON data"),
    ("尝试使用正则表达式直接提取content内容","try using regex to extract content directly"),
    ("需要Process转义的双引号和其他特殊字符","need to handle escaped quotes and special characters"),
    ("使用JSON.parse解码转义字符","decode escaped characters using JSON.parse"),
    ("解码失败，直接使用原始匹配内容","decoding failed; use raw matched content"),
    ("如果提取到内容，拼接并返回","if content extracted, join and return"),
    ("检查特殊字符Whether存在","check whether special characters exist"),
    ("提取内容Contains特殊字符，确保正确Process","extracted content contains special characters; ensure correct handling"),
    ("没有找到内容","no content found"),
    ("从SSE提取内容失败","failed to extract content from SSE"),
    ("直接从原始SSE事件数组中提取纯文本内容，不使用JSON解析","extract plain text directly from raw SSE event array without JSON parsing"),
    ("这个方法专门Process一个字符一个事件的极端情况","this method handles the extreme case of one character per event"),
    ("SSE事件数组，每个事件格式为data:{\"message\":{\"content\":\"字符\"}}","SSE event array; each event formatted as data:{\"message\":{\"content\":\"char\"}}"),
    ("记录特殊字符匹配情况","log special character matches"),
    ("使用forEach避免linter错误","use forEach to avoid linter errors"),
    ("使用直接字符串匹配，避免JSON解析错误","use direct string matching to avoid JSON parse errors"),
    ("Get引号内的内容并Process转义","get the content inside quotes and handle escapes"),
    ("使用JSON.parseProcess转义字符","use JSON.parse to handle escaped characters"),
    ("检查特殊字符","check special characters"),
    ("解析失败时，直接使用原始匹配内容","on parse failure, use raw matched content"),
    ("记录特殊字符情况","log special character situation"),
    ("检查Whether是SSE格式","check whether it is SSE format"),
    ("比较两种方法的结果，选择Contains特殊字符更多的那个","compare both methods and choose the one preserving more special characters"),
    ("检查Whether是当前测试会话","check whether it is the current test session"),
    ("忽略过时的测试会话回调","ignore outdated test session callback"),
    ("检查Whether是当前测试会话命令","check whether it is the current test session command"),
    ("收到命令: ","commands received: "),
    ("没有命令需要Process","no commands need processing"),
    ("标记命令Process开始","mark command processing start"),
    ("如果有命令，更新消息内容指示正在Process命令","if commands exist, update message content indicating processing commands"),
    ("完成Process","complete processing"),
    ("忽略过时的测试会话命令","ignore outdated test session command"),
    ("使用完整响应文本测试StreamProcessor组件功能","test StreamProcessor with complete response text"),
    ("使用完整的SSE事件字符串","test using full SSE event string"),
    ("接收单个Contains多行SSE数据的字符串","accept a single string containing multiple lines of SSE data"),
    ("自动分割Process","automatically split and process"),
    ("如果内容为空，直接返回","if content is empty, return directly"),
    ("内容不是SSE格式，作为原始内容Process","content is not SSE format; process as raw content"),
    ("提取到原始内容，长度: ","extracted raw content, length: "),
    ("使用小块大小确保特殊字符Process正确","use small chunk size to ensure special characters handled correctly"),
    ("消息ID","message ID"),
    ("创建mock SSE stream","create mock SSE stream"),
    ("获Cancel息最新状态","get latest message state"),
    ("更新消息状态为done","update message status to done"),
    ("确保是data:开头","ensure it starts with data:"),
    ("使用return代替continue","use return instead of continue"),
    ("尝试解析JSON","try parsing JSON"),
    ("提取的纯文本内容","extracted plain text content"),
    ("避免使用++","avoid using ++"),
    ("检查参数合法性","validate parameters"),
    ("开始新的原始内容测试会话","start new raw content test session"),
    ("原始内容长度","raw content length"),
    ("检查内容WhetherContains特殊字符","check whether content contains special characters"),
    ("记录特殊字符","log special characters"),
    ("检测到内容Contains特殊字符，使用更小的块大小和精确编码","detected special characters; use smaller chunk size with precise encoding"),
    ("简单记录特殊字符存在","log that special characters exist"),
    ("发现特殊字符，将使用更严格的Process方式","found special characters; using stricter processing"),
    ("打印含有特殊字符的一小段样本","print a short sample containing special characters"),
    ("特殊字符样本位置: ${i}, 上下文: \"","special character sample at position ${i}, context: \""),
    ("将完整内容分割成小块，每个块都成为一个SSE事件","split the full content into chunks; each chunk becomes an SSE event"),
    ("使用更小的块大小Process特殊字符，确保编码正确","use smaller chunk size for special characters to ensure correct encoding"),
    ("使用块大小","using chunk size"),
]
path = pathlib.Path(r"frontend/delightful-web/src/opensource/pages/flow/components/FlowAssistant/useTestFunctions.tsx")
text = path.read_text(encoding="utf-8")
for old, new in replacements:
    text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
print("done")
