#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import json
import re

# Targeted translations for remaining Chinese text
targeted_translations = {
    # Descriptions and labels
    "description": "description",
    "explanation": "explanation",
    "title": "title",
    "label": "label",
    "name": "name",
    "type": "type",
    "category": "category",
    "category": "category",
    "group": "group",
    "theme": "topic",
    "main": "main",
    "secondary": "secondary",
    "content": "content",
    "details": "details",
    "detailed": "detailed",
    "introduction": "introduction",
    "overview": "overview",
    "summary": "summary",
    "abstract": "abstract",
    "key points": "key points",
    "core": "core",
    "basic": "basic",
    "advanced": "advanced",
    "getting started": "getting started",
    "tutorial": "tutorial",
    "guide": "guide",
    "manual": "manual",
    "reference": "reference",
    "resource": "resource",
    "tool": "tool",
    "utility": "utility",
    "application": "application",
    "program": "program",
    "script": "script",
    
    # Common test/example patterns
    "example": "example",
    "example": "example",
    "sample": "sample",
    "case": "case",
    "use case": "use case",
    "scenario": "scenario",
    "instance": "instance",
    "sample": "sample",
    "template": "template",
    "prototype": "prototype",
    "framework": "framework",
    "architecture": "architecture",
    "design": "design",
    "pattern": "pattern",
    "specification": "specification",
    "standard": "standard",
    "convention": "convention",
    "best practice": "best practice",
    "experience": "experience",
    "tip": "tip",
    "method": "method",
    "technology": "technology",
    "learning": "learning",
    "training": "training",
    "exam": "exam",
    "quiz": "quiz",
    "exercise": "exercise",
    "assignment": "assignment",
    "project": "project",
    "task": "task",
    "work": "work",
    "position": "position",
    "title": "title",
    "role": "role",
    "permission": "permission",
    "authorization": "authorization",
    "authentication": "authentication",
    "login": "login",
    "register": "register",
    "logout": "logout",
    "exit": "exit",
    "session": "session",
    "user": "user",
    "account": "account",
    "password": "password",
    "verify": "verification",
    "confirm": "confirmation",
    "reminder": "reminder",
    "notification": "notification",
    "message": "message",
    "hint": "hint",
    "suggestion": "suggestion",
    "recommend": "recommendation",
    "featured": "featured",
    "popular": "popular",
    "new": "new",
    "update": "update",
    "improvement": "improvement",
    "fix": "fix",
    "correction": "correction",
    "adjustment": "adjustment",
    "optimization": "optimization",
    "enhancement": "enhancement",
    "extension": "extension",
    "supplement": "supplement",
    "perfect": "perfect",
    "complete": "complete",
    "comprehensive": "comprehensive",
    "part": "part",
    "fragment": "fragment",
    "node": "node",
    "link": "link",
    "connection": "connection",
    "relationship": "relationship",
    "dependency": "dependency",
    "association": "association",
    "mapping": "mapping",
    "corresponding": "corresponding",
    "related": "related",
    "similar": "similar",
    "different": "different",
    "distinction": "distinction",
    "difference": "difference",
    "feature": "feature",
    "characteristic": "characteristic",
    "property": "property",
    "attribute": "attribute",
    "parameter": "parameter",
    "variable": "variable",
    "value": "value",
    "default": "default",
    "custom": "custom",
    "predefined": "predefined",
    "system": "system",
    "user-defined": "user-defined",
    "configuration": "configuration",
    "settings": "settings",
    "option": "option",
    "preference": "preference",
    "theme": "theme",
    "skin": "skin",
    "appearance": "appearance",
    "style": "style",
    "layout": "layout",
    "typography": "typography",
    "color": "color",
    "font": "font",
    "size": "size",
    "width": "width",
    "height": "height",
    "depth": "depth",
    "distance": "distance",
    "spacing": "spacing",
    "margin": "margin",
    "fill": "padding",
    "border": "border",
    "shadow": "shadow",
    "opacity": "opacity",
    "gradient": "gradient",
    "threshold": "threshold",
    "range": "range",
    "boundary": "boundary",
    "limit": "limit",
    "constraint": "constraint",
    "regular": "rule",
    "condition": "condition",
    "logic": "logic",
    "algorithm": "algorithm",
    "formula": "formula",
    "expression": "expression",
    "function": "function",
    "equation": "equation",
    "calculation": "calculation",
    "operation": "operation",
    "operation": "operation",
    "action": "action",
    "event": "event",
    "trigger": "trigger",
    "invoke": "invoke",
    "execute": "execute",
    "run": "run",
    "start": "start",
    "stop": "stop",
    "pause": "pause",
    "continue": "resume",
    "restart": "restart",
    "rollback": "rollback",
    "undo": "undo",
    "redo": "redo",
    "save": "save",
    "load": "load",
    "import": "import",
    "export": "export",
    "backup": "backup",
    "restore": "restore",
    "delete": "delete",
    "clear": "clear",
    "reset": "reset",
    "initialize": "initialize",
    "destroy": "destroy",
    "create": "create",
    "generate": "generate",
    "build": "build",
    "compile": "compile",
    "package": "package",
    "deploy": "deploy",
    "publish": "publish",
    "launch": "launch",
    "offline": "offline",
    "maintain": "maintain",
    "monitor": "monitor",
    "manage": "manage",
    "control": "control",
    "debug": "debug",
    "test": "test",
    "verify": "verify",
    "check": "check",
    "scan": "scan",
    "analyze": "analyze",
    "statistics": "statistics",
    "report": "report",
    "log": "log",
    "output": "output",
    "input": "input",
    "return": "return",
    "response": "response",
    "request": "request",
    "send": "send",
    "receive": "receive",
    "read": "read",
    "write": "write",
    "append": "append",
    "edit": "edit",
    "modify": "modify",
    "replication": "copy",
    "paste": "paste",
    "cut": "cut",
    "select": "select",
    "search": "search",
    "replace": "replace",
    "filter": "filter",
    "sort": "sort",
    "group": "group",
    "aggregate": "aggregate",
    "merge": "merge",
    "split": "split",
    "truncate": "truncate",
    "fill": "fill",
    "remove": "remove",
    "keep": "keep",
    "ignore": "ignore",
    "skip": "skip",
    "abort": "abort",
    "wrong": "error",
    "exception": "exception",
    "warning": "warning",
    "info": "info",
    "debug": "debug",
    "success": "success",
    "failure": "failure",
    "complete": "complete",
    "interrupted": "interrupted",
    "timeout": "timeout",
    "async": "async",
    "sync": "sync",
    "blocking": "blocking",
    "non-blocking": "non-blocking",
    "concurrent": "concurrent",
    "parallel": "parallel",
    "sequential": "sequential",
    "queue": "queue",
    "stack": "stack",
    "buffer": "buffer",
    "caching": "cache",
    "memory": "memory",
    "storage": "storage",
    "database": "database",
    "file system": "file system",
    "network": "network",
    "local": "local",
    "remote": "remote",
    "server": "server",
    "client": "client",
    "proxy": "proxy",
    "gateway": "gateway",
    "load balancing": "load balancing",
    "redundancy": "redundancy",
    "backup": "backup",
    "restore": "recovery",
    "sync": "synchronization",
    "replication": "replication",
    "distributed": "distributed",
    "cluster": "cluster",
    "node": "node",
    "master-slave": "master-slave",
    "master-master": "master-master",
    "failover": "failover",
    "health check": "health check",
    "heartbeat": "heartbeat",
    "timeout": "timeout",
    "retry": "retry",
    "circuit breaker": "circuit breaker",
    "isolation": "isolation",
    "rate limiting": "rate limiting",
    "fuse": "fuse",
    "degradation": "degradation",
    "caching": "caching",
    "preload": "preload",
    "lazy load": "lazy load",
    "on-demand loading": "on-demand loading",
    "incremental loading": "incremental loading",
    "pagination": "pagination",
    "scrolling": "scrolling",
    "virtual scrolling": "virtual scrolling",
    "infinite scrolling": "infinite scrolling",
    "loading": "loading",
    "loaded": "loaded",
    "load failed": "load failed",
    "reload": "reload",
    "refresh": "refresh",
    "update": "update",
    "sync": "sync",
    "unsync": "unsync",
    "waiting": "waiting",
    "ready": "ready",
    "ready": "ready",
    "active": "active",
    "inactive": "inactive",
    "enabled": "enabled",
    "disabled": "disabled",
    "visible": "visible",
    "hide": "hidden",
    "show": "show",
    "hide": "hide",
    "open": "open",
    "close": "close",
    "expand": "expand",
    "collapse": "collapse",
    "increase": "increase",
    "decrease": "decrease",
    "maximize": "maximize",
    "minimize": "minimize",
    "restore": "restore",
    "fullscreen": "fullscreen",
    "exit fullscreen": "exit fullscreen",
    "previous": "previous",
    "next": "next",
    "first": "first",
    "last": "last",
    "top": "top",
    "bottom": "bottom",
    "start": "start",
    "end": "end",
    "middle": "middle",
    "left": "left",
    "right": "right",
    "above": "above",
    "below": "below",
    "inside": "inside",
    "outside": "outside",
    "front": "front",
    "back": "back",
    "top": "top",
    "bottom": "bottom",
    "beside": "beside",
    "near": "near",
    "far": "far",
    "close": "close",
    "separate": "separate",
    "side by side": "side by side",
    "overlap": "overlap",
    "cross": "cross",
    "parallel": "parallel",
    "vertical": "vertical",
    "horizontal": "horizontal",
    "diagonal": "diagonal",
    "symmetric": "symmetric",
    "asymmetric": "asymmetric",
    "regular": "regular",
    "irregular": "irregular",
    "uniform": "uniform",
    "non-uniform": "non-uniform",
    "smooth": "smooth",
    "rough": "rough",
    "sharp": "sharp",
    "soft": "soft",
    "bright": "bright",
    "dark": "dark",
    "clear": "clear",
    "blurry": "blurry",
    "sharp": "sharp",
    "dull": "dull",
    "fine": "fine",
    "coarse": "coarse",
    "small": "small",
    "large": "large",
    "short": "short",
    "long": "long",
    "narrow": "narrow",
    "wide": "wide",
    "thin": "thin",
    "thick": "thick",
    "light": "light",
    "heavy": "heavy",
    "fast": "fast",
    "slow": "slow",
    "high": "high",
    "low": "low",
    "strong": "strong",
    "weak": "weak",
    "many": "many",
    "few": "few",
    "all": "all",
    "part": "part",
    "most": "most",
    "minority": "minority",
    "majority": "majority",
    "small part": "small part",
    "some": "some",
    "several": "several",
    "some": "some",
    "some": "some",
    "any": "any",
    "each": "each",
    "every": "every",
    "every time": "every time",
    "occasionally": "occasionally",
    "often": "often",
    "always": "always",
    "never": "never",
    "rarely": "rarely",
    "always": "always",
    "might": "possible",
    "impossible": "impossible",
    "maybe": "maybe",
    "certainly": "certainly",
    "definitely": "definitely",
    "negative": "negative",
    "confirm": "confirm",
    "uncertain": "uncertain",
    "real": "real",
    "virtual": "virtual",
    "actual": "actual",
    "theoretical": "theoretical",
    "valid": "valid",
    "invalid": "invalid",
    "useful": "useful",
    "useless": "useless",
    "good": "good",
    "bad": "bad",
    "correct": "correct",
    "wrong": "wrong",
    "true": "true",
    "false": "false",
    "yes": "yes",
    "no": "no",
    "have": "have",
    "no": "no",
    "exist": "exist",
    "not exist": "not exist",
    "life": "life",
    "existence": "existence",
    "appear": "appear",
    "disappear": "disappear",
    "growth": "growth",
    "decline": "decline",
    "rise": "rise",
    "fall": "fall",
    "start": "begin",
    "end": "end",
    "start": "start",
    "close": "close",
    "open": "open",
    "forbid": "forbid",
    "allow": "allow",
    "agree": "agree",
    "reject": "reject",
    "accept": "accept",
    "refuse": "refuse",
    "confirm": "confirm",
    "deny": "deny",
    "support": "support",
    "against": "oppose",
    "favor": "favor",
    "against": "against",
    "recommend": "recommend",
    "not recommended": "not recommended",
    "must": "must",
    "should": "should",
    "can": "can",
    "might": "might",
    "might not": "might not",
    "need": "need",
    "not need": "not need",
    "want": "want",
    "not want": "not want",
    "willing": "willing",
    "unwilling": "unwilling",
    "try": "try",
    "give up": "give up",
    "persist": "persist",
    "change": "change",
    "keep": "keep",
    "increase": "increase",
    "decrease": "decrease",
    "multiply": "multiply",
    "divide": "divide",
    "add": "add",
    "subtract": "subtract",
    "and": "and",
    "or": "or",
    "not": "not",
    "if": "if",
    "then": "then",
    "else": "else",
    "unless": "unless",
    "because": "because",
    "due to": "due to",
    "despite": "despite",
    "although": "although",
    "and": "and",
    "but": "but",
    "however": "however",
    "therefore": "therefore",
    "thus": "thus",
    "for": "for",
    "about": "about",
    "as for": "as for",
    "then": "then",
    "in": "in",
    "from": "from",
    "to": "to",
    "at": "at",
    "by": "by",
    "when": "when",
    "time": "time",
    "before": "before",
    "after": "after",
    "during": "during",
    "between": "between",
    "among": "among",
    "outside": "outside",
    "inside": "inside",
    "above": "above",
    "below": "below",
    "left": "left",
    "right": "right",
    "is": "is",
    "already": "already",
    "not yet": "not yet",
    "once": "once",
    "never": "never",
    "start": "start",
    "continue": "continue",
    "stop": "stop",
}

def clean_json_translations(filepath):
    """Clean up translations in JSON files"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        def clean_value(val):
            """Recursively clean values"""
            if isinstance(val, str):
                for chinese, english in sorted(targeted_translations.items(), 
                                              key=lambda x: len(x[0]), reverse=True):
                    if chinese in val:
                        val = val.replace(chinese, english)
                return val
            elif isinstance(val, dict):
                return {k: clean_value(v) for k, v in val.items()}
            elif isinstance(val, list):
                return [clean_value(item) for item in val]
            return val
        
        cleaned_data = clean_value(data)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(cleaned_data, f, ensure_ascii=False, indent=2)
        
        return True
    except:
        return False

def clean_text_file(filepath):
    """Clean up translations in text files"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        
        for chinese, english in sorted(targeted_translations.items(), 
                                      key=lambda x: len(x[0]), reverse=True):
            if chinese in content:
                content = content.replace(chinese, english)
        
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            return True
        
        return False
    except:
        return False

def main():
    """Main function"""
    base_dir = "c:\\Users\\kubew\\magic"
    modified = 0
    
    for root, dirs, files in os.walk(base_dir):
        dirs[:] = [d for d in dirs if d not in {'node_modules', '.git', 'dist', 'build', '.dumi', '__pycache__'}]
        
        for file in files:
            filepath = os.path.join(root, file)
            
            # Skip large files
            if os.path.getsize(filepath) > 10_000_000:
                continue
            
            if file.endswith('.json'):
                if clean_json_translations(filepath):
                    modified += 1
                    print(f"✓ {os.path.relpath(filepath, base_dir)}")
            elif file.endswith(('.md', '.yaml', '.yml', '.html', '.ts', '.tsx', '.py')):
                if clean_text_file(filepath):
                    modified += 1
                    print(f"✓ {os.path.relpath(filepath, base_dir)}")
    
    print(f"\n✅ Cleaned {modified} files")

if __name__ == '__main__':
    main()
