#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Helper script to create translation mappings for Chinese to English
"""

# Translation mappings
TRANSLATIONS = {
    # Common phrases
    "获取": "get",
    "设置": "set",
    "检查": "check",
    "添加": "add",
    "移除": "remove",
    "删除": "delete",
    "加载": "load",
    "保存": "save",
    "解析": "parse",
    "验证": "validate",
    "处理": "handle",
    "初始化": "initialize",
    "创建": "create",
    "更新": "update",
    "查询": "query",
    "转换": "convert",
    "格式化": "format",
    "计算": "calculate",
    "执行": "execute",
    "调用": "call",
    "返回": "return",
    "抛出": "throw",
    "成功": "successfully",
    "失败": "failed",
    "错误": "error",
    "警告": "warning",
    "消息": "message",
    "内容": "content",
    "字段": "field",
    "参数": "parameter",
    "配置": "configuration",
    "属性": "attribute",
    "方法": "method",
    "函数": "function",
    "类型": "type",
    "值": "value",
    "默认": "default",
    "可选": "optional",
    "必需": "required",
    "有效": "valid",
    "无效": "invalid",
    "空": "empty",
    "为空": "is empty",
    "不能为空": "cannot be empty",
    "缺少": "missing",
    "存在": "exists",
    "不存在": "does not exist",
    "已存在": "already exists",
    "文件": "file",
    "目录": "directory",
    "路径": "path",
    "名称": "name",
    "编号": "ID",
    "标识符": "identifier",
    "索引": "index",
    "列表": "list",
    "字典": "dictionary",
    "对象": "object",
    "实例": "instance",
    "数组": "array",
    "字符串": "string",
    "数字": "number",
    "布尔值": "boolean",
    "日期": "date",
    "时间": "time",
    "时间戳": "timestamp",
    "版本": "version",
    "状态": "status",
    "结果": "result",
    "响应": "response",
    "请求": "request",
    "数据": "data",
    "信息": "information",
    "详情": "details",
    "摘要": "summary",
    "描述": "description",
    "说明": "explanation",
    "注释": "comment",
    "备注": "note",
    "提示": "prompt",
    "模型": "model",
    "工具": "tool",
    "代理": "agent",
    "聊天": "chat",
    "历史": "history",
    "记录": "record",
    "日志": "log",
    "输入": "input",
    "输出": "output",
    "总计": "total",
    "数量": "count",
    "大小": "size",
    "长度": "length",
    "位置": "position",
    "开始": "start",
    "结束": "end",
    "前": "before",
    "后": "after",
    "当前": "current",
    "上一个": "previous",
    "下一个": "next",
    "最后": "last",
    "第一个": "first",
    "所有": "all",
    "任何": "any",
    "没有": "no",
    "是": "yes",
    "否": "no",
    "真": "true",
    "假": "false",
    "启用": "enable",
    "禁用": "disable",
    "已启用": "enabled",
    "已禁用": "disabled",
    "压缩": "compression",
    "展开": "expand",
    "折叠": "collapse",
    "打开": "open",
    "关闭": "close",
    "显示": "show",
    "隐藏": "hide",
    "可见": "visible",
    "不可见": "invisible",
    "已显示": "shown",
    "已隐藏": "hidden",
    "用户": "user",
    "系统": "system",
    "助手": "assistant",
    "角色": "role",
    "权限": "permission",
    "令牌": "token",
    "令牌数": "token count",
    "成本": "cost",
    "价格": "price",
    "费用": "charge",
    "货币": "currency",
    "汇率": "exchange rate",
    "未知": "unknown",
    "其他": "other",
    "未定义": "undefined",
    "或": "or",
    "且": "and",
    "如果": "if",
    "则": "then",
    "否则": "else",
    "当": "when",
    "直到": "until",
    "从": "from",
    "到": "to",
    "为": "as",
    "的": "",
    "了": "",
    "在": "in",
    "于": "at",
    "对": "for",
    "与": "with",
    "将": "will",
    "已": "has",
    "被": "be",
    "将要": "will be",
    "已经": "already",
    "正在": "is",
    "尝试": "try",
    "重试": "retry",
    "跳过": "skip",
    "忽略": "ignore",
    "继续": "continue",
    "中断": "interrupt",
    "停止": "stop",
    "暂停": "pause",
    "恢复": "resume",
    "完成": "complete",
    "取消": "cancel",
    "确认": "confirm",
    "拒绝": "reject",
    "接受": "accept",
    "同意": "agree",
    "不同意": "disagree",
    "是否": "whether",
    "可以": "can",
    "不能": "cannot",
    "应该": "should",
    "不应该": "should not",
    "必须": "must",
    "不必": "need not",
    "允许": "allow",
    "不允许": "not allow",
    "需要": "need",
    "不需要": "do not need",
    "支持": "support",
    "不支持": "not support",
    "包含": "contain",
    "不包含": "not contain",
    "符合": "conform",
    "不符合": "not conform",
    "匹配": "match",
    "不匹配": "not match",
    "相等": "equal",
    "不相等": "not equal",
    "相同": "same",
    "不同": "different",
    "大于": "greater than",
    "小于": "less than",
    "等于": "equal to",
    "不等于": "not equal to",
    "大于等于": "greater than or equal to",
    "小于等于": "less than or equal to",
}

# Context-specific translations
CONTEXT_TRANSLATIONS = {
    "聊天记录": "chat history",
    "聊天历史": "chat history",
    "消息列表": "message list",
    "消息数量": "message count",
    "令牌数量": "token count",
    "令牌使用": "token usage",
    "成本报告": "cost report",
    "价格信息": "pricing information",
    "模型配置": "model configuration",
    "工具配置": "tool configuration",
    "代理配置": "agent configuration",
    "压缩配置": "compression configuration",
    "压缩率": "compression ratio",
    "压缩后": "after compression",
    "压缩前": "before compression",
    "原始消息": "original message",
    "压缩消息": "compressed message",
    "保留消息": "preserved message",
    "最近消息": "recent message",
    "历史消息": "historical message",
    "系统消息": "system message",
    "用户消息": "user message",
    "助手消息": "assistant message",
    "工具消息": "tool message",
    "工具调用": "tool call",
    "工具结果": "tool result",
    "函数调用": "function call",
    "函数参数": "function argument",
    "函数名称": "function name",
    "返回值": "return value",
    "错误信息": "error message",
    "警告信息": "warning message",
    "调试信息": "debug information",
    "日志信息": "log information",
    "异常信息": "exception information",
    "堆栈跟踪": "stack trace",
    "文件路径": "file path",
    "文件名": "filename",
    "目录路径": "directory path",
    "工作目录": "working directory",
    "当前目录": "current directory",
    "配置文件": "configuration file",
    "数据文件": "data file",
    "日志文件": "log file",
    "临时文件": "temporary file",
    "缓存文件": "cache file",
    "备份文件": "backup file",
    "源文件": "source file",
    "目标文件": "target file",
    "输入文件": "input file",
    "输出文件": "output file",
    "文件大小": "file size",
    "文件类型": "file type",
    "文件扩展名": "file extension",
    "文件权限": "file permission",
    "文件所有者": "file owner",
    "创建时间": "creation time",
    "修改时间": "modification time",
    "访问时间": "access time",
    "最后修改": "last modified",
    "用户ID": "user ID",
    "会话ID": "session ID",
    "请求ID": "request ID",
    "事务ID": "transaction ID",
    "任务ID": "task ID",
    "进程ID": "process ID",
    "线程ID": "thread ID",
    "唯一标识": "unique identifier",
    "主键": "primary key",
    "外键": "foreign key",
    "索引键": "index key",
    "默认值": "default value",
    "初始值": "initial value",
    "最小值": "minimum value",
    "最大值": "maximum value",
    "平均值": "average value",
    "总和": "sum",
    "总计": "total",
    "百分比": "percentage",
    "比率": "ratio",
    "比例": "proportion",
    "数量": "quantity",
    "计数": "count",
    "次数": "times",
    "频率": "frequency",
    "周期": "period",
    "间隔": "interval",
    "超时": "timeout",
    "延迟": "delay",
    "持续时间": "duration",
    "耗时": "elapsed time",
    "剩余时间": "remaining time",
    "开始时间": "start time",
    "结束时间": "end time",
    "当前时间": "current time",
    "时间戳": "timestamp",
    "时区": "timezone",
    "日期格式": "date format",
    "时间格式": "time format",
    "数字格式": "number format",
    "字符串格式": "string format",
    "格式化字符串": "formatted string",
    "正则表达式": "regular expression",
    "模式匹配": "pattern matching",
    "通配符": "wildcard",
    "占位符": "placeholder",
    "分隔符": "delimiter",
    "分隔符": "separator",
    "前缀": "prefix",
    "后缀": "suffix",
    "中缀": "infix",
    "空格": "space",
    "制表符": "tab",
    "换行符": "newline",
    "回车符": "carriage return",
    "空白字符": "whitespace",
    "特殊字符": "special character",
    "转义字符": "escape character",
    "编码": "encoding",
    "解码": "decoding",
    "加密": "encryption",
    "解密": "decryption",
    "哈希": "hash",
    "校验": "checksum",
    "签名": "signature",
    "验证": "verification",
    "认证": "authentication",
    "授权": "authorization",
    "会话": "session",
    "令牌": "token",
    "密钥": "key",
    "密码": "password",
    "用户名": "username",
    "账号": "account",
    "登录": "login",
    "登出": "logout",
    "注册": "register",
    "注销": "unregister",
    "激活": "activate",
    "停用": "deactivate",
    "锁定": "lock",
    "解锁": "unlock",
    "冻结": "freeze",
    "解冻": "unfreeze",
    "启用": "enable",
    "禁用": "disable",
    "打开": "open",
    "关闭": "close",
    "连接": "connect",
    "断开": "disconnect",
    "绑定": "bind",
    "解绑": "unbind",
    "附加": "attach",
    "分离": "detach",
    "挂载": "mount",
    "卸载": "unmount",
    "安装": "install",
    "卸载": "uninstall",
    "部署": "deploy",
    "回滚": "rollback",
    "发布": "release",
    "撤销": "revoke",
    "恢复": "restore",
    "备份": "backup",
    "导入": "import",
    "导出": "export",
    "上传": "upload",
    "下载": "download",
    "同步": "synchronize",
    "异步": "asynchronous",
    "并发": "concurrent",
    "并行": "parallel",
    "串行": "serial",
    "顺序": "sequential",
    "随机": "random",
    "排序": "sort",
    "过滤": "filter",
    "搜索": "search",
    "查找": "find",
    "替换": "replace",
    "插入": "insert",
    "追加": "append",
    "前置": "prepend",
    "删除": "delete",
    "清空": "clear",
    "重置": "reset",
    "刷新": "refresh",
    "重新加载": "reload",
    "重新启动": "restart",
    "重新初始化": "reinitialize",
    "重新配置": "reconfigure",
    "重新连接": "reconnect",
    "重新绑定": "rebind",
    "重新编译": "recompile",
    "重新构建": "rebuild",
    "重新部署": "redeploy",
    "重新发布": "republish",
    "重新计算": "recalculate",
    "重新评估": "reevaluate",
    "重新验证": "revalidate",
    "重新认证": "reauthenticate",
    "重新授权": "reauthorize",
}

if __name__ == "__main__":
    print("Translation helper ready")
    print(f"Total basic translations: {len(TRANSLATIONS)}")
    print(f"Total context translations: {len(CONTEXT_TRANSLATIONS)}")
