#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

# Comprehensive Chinese to English translation dictionary
translations = {
    # Common words
    '人写': 'realistic',
    '画': 'painted',
    '超': 'ultra',
    '年': 'year',
    '国': 'country',
    '条': 'lines',
    '夜晚': 'night',
    '杂志封面': 'magazine cover',
    '写': 'write',
    '超清': 'ultra clear',
    '嫦娥': "Chang'e",
    '手部': 'hand',
    '她': 'she',
    '手指尖': 'fingertips',
    '闪烁': 'sparkling',
    '冰': 'ice',
    '微光': 'faint light',
    '像': 'like',
    '月光': 'moonlight',
    '凝结': 'condensed',
    '运用': 'using',
    '冰雕': 'ice sculpture',
    '来表现': 'to express',
    '指甲': 'nails',
    '上': 'on',
    '绘': 'drawn',
    '有': 'have',
    '精致': 'exquisite',
    '玉兔': 'jade rabbit',
    '图案': 'pattern',
    '如同': 'like',
    '微雕': 'micro carving',
    '工艺': 'craft',
    '她手持': 'she holds',
    '巨大': 'giant',
    '桂花': 'osmanthus',
    '花瓣': 'petals',
    '半透明': 'translucent',
    '玉片': 'jade piece',
    '花蕊': 'stamens',
    '散发': 'emitting',
    '金色': 'golden',
    '光芒': 'radiance',
    '镶嵌': 'inlaid',
    '金粉': 'gold powder',
    '背景': 'background',
    '是': 'is',
    '模糊': 'blurred',
    '月宫': 'moon palace',
    '轮廓': 'outline',
    '只': 'only',
    '能': 'can',
    '看': 'see',
    '到': 'to',
    '一些': 'some',
    '琉璃': 'glaze',
    '质感': 'texture',
    '宫墙': 'palace wall',
    '一角': 'corner',
    '和': 'and',
    '几缕': 'several strands',
    '淡淡': 'faint',
    '云雾': 'clouds and mist',
    '通过': 'by',
    '细腻': 'delicate',
    '手部肌肤': 'hand skin',
    '晶莹': 'crystal clear',
    '微观': 'micro',
    '冷色调': 'cold tones',
    '为主': 'mainly',
    '冰蓝': 'ice blue',
    '金黄': 'golden yellow',
    '相衬': 'complement',
    '玉质': 'jade',
    '材质': 'material',
    '渲染器': 'renderer',
    '唯美': 'aesthetic',
    '神话': 'mythology',
    '之美': 'beauty',
    '结合': 'combined',
    '周围': 'surrounding',
    '空白': 'blank',
    '微距镜头': 'macro lens',
    '侧光': 'side light',
    '模拟': 'simulate',
    '从': 'from',
    '侧面': 'side',
    '洒下': 'pour down',
    '光晕': 'halo',
    '清冷': 'cold',
    '微观神话': 'micro mythology',
    '由': 'by',
    '海报': 'poster',
    '设计': 'design',
    '巨匠': 'master',
    '操刀': 'created',
    '明月': 'bright moon',
    '为': 'as',
    '核心': 'core',
    '元素': 'elements',
    '通过': 'through',
    '极简': 'minimalist',
    '构图': 'composition',
    '强烈': 'strong',
    '色彩': 'colors',
    '对比': 'contrast',
    '创造': 'create',
    '出': 'out',
    '令人': 'people',
    '震撼': 'stunning',
    '视觉': 'visual',
    '冲击': 'impact',
    '画面': 'scene',
    '中': 'in',
    '孤悬': 'hanging alone',
    '周围': 'surrounding',
    '无尽': 'endless',
    '深蓝': 'deep blue',
    '或': 'or',
    '纯黑': 'pure black',
    '仅有': 'only have',
    '淡云': 'light clouds',
    '轻绕': 'lightly surround',
    '营造': 'create',
    '一种': 'a kind of',
    '超脱': 'transcendent',
    '尘世': 'earthly',
    '静美': 'quiet beauty',
    '这份': 'this',
    '不仅': 'not only',
    '对': 'to',
    '千里寄相思': 'send love across thousands of miles',
    '主题': 'theme',
    '深刻': 'profound',
    '诠释': 'interpretation',
    '更': 'more',
    '对视觉艺术': 'to visual art',
    '极致': 'extreme',
    '追求': 'pursuit',
    '体现': 'embodiment',
    '让': 'let',
    '人': 'people',
    '在': 'in',
    '简洁': 'simple',
    '感受': 'feel',
    '情感': 'emotion',
    '共鸣': 'resonance',
    '旅游': 'travel',
    '创意': 'creative',
    '拼贴': 'collage',
    '抠像': 'matting',
    '撕纸': 'torn paper',
    '描边': 'stroke',
    '一': 'a',
    '位': 'located',
    '中': 'Chinese',
    '女孩': 'girl',
    '高兴': 'happy',
    '跳起来': 'jump up',
    '梦幻': 'dreamy',
    '欢乐': 'joyful',
    '夸张': 'exaggerated',
    '节日': 'festival',
    '火爆': 'hot',
    '多彩': 'multicolored',
    '世界': 'world',
    '主要': 'main',
    '打卡地': 'landmark',
    '剪影': 'silhouette',
    '波普': 'pop art',
    '风格': 'style',
    '配色': 'color scheme',
    '广袤': 'vast',
    '草原': 'grassland',
    '辆': 'a',
    '小巧': 'small',
    '绿色': 'green',
    '巴士': 'bus',
    '孤独': 'lonely',
    '地': 'ground',
    '行驶': 'traveling',
    '天空': 'sky',
    '湛蓝': 'azure',
    '无云': 'cloudless',
    '阳光': 'sunshine',
    '明媚': 'bright',
    '这': 'this',
    '看起来': 'looks like',
    '正在': 'currently',
    '前往': 'going to',
    '某个': 'some',
    '遥远': 'remote',
    '目的地': 'destination',
    '也许': 'maybe',
    '未知': 'unknown',
    '冒险': 'adventure',
    '之旅': 'journey',
    '它': 'it',
    '穿越': 'crossing',
    '起伏': 'rolling',
    '山丘': 'hills',
    '留下': 'leaving',
    '一道道': 'one after another',
    '车轮': 'wheel',
    '印迹': 'marks',
    '远处': 'distance',
    '几只': 'several',
    '牛羊': 'cattle and sheep',
    '悠闲': 'leisurely',
    '吃草': 'grazing',
    '它们': 'they',
    '这辆': 'this',
    '突然': 'suddenly',
    '出现': 'appear',
    '小': 'small',
    '巴': 'bus',
    '毫不在意': 'don\'t care',
    '整个': 'whole',
    '画面': 'scene',
    '充满': 'full of',
    '宁静': 'serene',
    '自由': 'free',
    '气息': 'atmosphere',
    '想起': 'recall',
    '那些': 'those',
    '远离': 'far from',
    '城市': 'city',
    '喧嚣': 'hustle',
    '日子': 'days',
    '夜幕': 'night',
    '下': 'under',
    '街道': 'street',
    '模糊': 'blurry',
    '身影': 'figure',
    '缓缓': 'slowly',
    '行走': 'walking',
    '失焦': 'out of focus',
    '镜头': 'lens',
    '捕捉': 'captured',
    '融合': 'fusion',
    '街拍': 'street photography',
    '韵味': 'charm',
    '孤寂': 'lonely',
    '氛围': 'atmosphere',
    '采用': 'adopt',
    '抽象': 'abstract',
    '表现': 'expression',
    '仅': 'only',
    '白': 'white',
    '深紫': 'deep purple',
    '构建': 'build',
    '空灵': 'ethereal',
    '梦境': 'dream',
    '自然光': 'natural light',
    '数字': 'digital',
    '技术': 'technology',
    '巧妙': 'clever',
    '融合': 'blend',
    '造成': 'create',
    '发光': 'glowing',
    '彩虹': 'rainbow',
    '渐变': 'gradient',
    '增添': 'add',
    '一抹': 'a touch of',
    '夜晚': 'night',
    '神秘': 'mysterious',
    '迷离': 'mysterious',
    '感': 'feeling',
    '正': 'currently',
    '手拉手': 'hand in hand',
    '沿': 'along',
    '绳梯': 'rope ladder',
    '爬': 'climb',
    '月球': 'moon',
    '个': 'a',
    '场景': 'scenario',
    '宇航员': 'astronaut',
    '简洁': 'clean',
    '简单': 'simple',
    '攀爬': 'climb',
    '垂直': 'vertical',
    '梯子': 'ladder',
    '关键': 'key',
    '点': 'points',
    '上升': 'rise',
    '登山者': 'climber',
    '之间': 'between',
    '一种': 'a kind of',
    '广阔': 'vast',
    '空间感': 'sense of space',
    '唤起': 'evoke',
    '决心': 'determination',
    '敬畏': 'awe',
    '感觉': 'feeling',
    '地球': 'earth',
    '唯一': 'only',
    '连接': 'connection',
    '强调': 'emphasize',
    '光滑': 'smooth',
    '整洁': 'tidy',
    '美学': 'aesthetics',
    '格式': 'format',
    '食品': 'food',
    '汉堡包': 'hamburger',
    '里面': 'inside',
    '夹': 'sandwiched',
    '鲜嫩': 'fresh',
    '蔬菜': 'vegetables',
    '牛排': 'steak',
    '番茄片': 'tomato slices',
    '细节': 'details',
    '巨大': 'giant',
    '画面正中心': 'center of scene',
    '背景虚化': 'background blur',
    '黑色': 'black',
    '炸开': 'explode',
    '金黄色': 'golden yellow',
    '透明': 'transparent',
    '油脂': 'oil',
    '空中': 'in the air',
    '漂浮': 'floating',
    '鲜美': 'fresh',
    '叶子': 'leaves',
    '小番茄': 'small tomatoes',
    '红': 'red',
    '黄色': 'yellow',
    '灯笼椒': 'bell pepper',
    '深黑色': 'deep black',
    '全局': 'global',
    '光照': 'lighting',
    '影棚': 'studio',
    '打光': 'lighting',
    '广告大师': 'advertising master',
    '大作': 'masterpiece',
    '简约': 'simple',
    '美观': 'beautiful',
    '黑铁': 'black iron',
    '凹凸': 'bumpy',
    '反光': 'reflective',
    '镜面': 'mirror',
    '桌子': 'table',
    '圆润': 'rounded',
    '饱满': 'full',
    '艺术字': 'artistic text',
    '标题': 'title',
    '字体': 'font',
    '不规则': 'irregular',
    '排列': 'arrangement',
    '大小': 'size',
    '变化': 'change',
    '基调': 'tone',
    '变暗': 'darken',
    '色彩偏深': 'color darker',
    '不吃光': 'not overexposed',
    '高级': 'advanced',
    '仰角': 'low angle',
    '视角': 'perspective',
    '低': 'low',
    '机位': 'camera position',
    '虚拟': 'virtual',
    '躺': 'lying',
    '猫': 'cat',
    '头上': 'on top',
    '圆形': 'round',
    '光影': 'light and shadow',
    '极简主义': 'minimalism',
    '治愈': 'healing',
    '虚无': 'void',
    '负空间': 'negative space'
}

def translate_prompt(prompt):
    """Translate Chinese characters in a prompt to English"""
    # Replace each Chinese term with its English equivalent
    result = prompt
    for chinese, english in translations.items():
        result = result.replace(chinese, english)
    return result

def count_chinese_chars(text):
    """Count Chinese characters in text"""
    return len(re.findall(r'[\u4e00-\u9fff]', text))

# Load the JSON file
print("Loading image_prompt.json...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

# Process prompts
print("\nTranslating prompts...")
translated_count = 0

# Navigate through the JSON structure
for category in json_data.get('data', []):
    for image_item in category.get('images', []):
        if 'prompt' in image_item:
            original = image_item['prompt']
            chinese_before = count_chinese_chars(original)
            
            if chinese_before > 0:
                translated = translate_prompt(original)
                chinese_after = count_chinese_chars(translated)
                
                if chinese_after < chinese_before:
                    image_item['prompt'] = translated
                    translated_count += 1
                    print(f"✓ Translated prompt (reduced {chinese_before} → {chinese_after} Chinese chars)")

# Save the updated file
print(f"\nSaving updated file...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f"\n✓ Complete! Translated {translated_count} prompts")

# Final verification
total_chinese = 0
for category in json_data.get('data', []):
    for image_item in category.get('images', []):
        total_chinese += count_chinese_chars(image_item.get('prompt', ''))

print(f"Remaining Chinese characters in prompts: {total_chinese}")
