#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

# Final targeted mappings for remaining top characters
char_translations = {
    '乎': '',
    '尾': 'tail',
    '披': 'drape',
    '逸': 'elegant',
    '铅': 'lead',
    '辛': 'spicy',
    '幕': 'curtain',
    '融': 'blend',
    '踪': 'trace',
    '楼': 'building',
    '颜': 'color',
    '恶': 'evil',
    '园': 'garden',
    '剪': 'cut',
    '礼': 'gift',
    '墙': 'wall',
    '荷': 'lotus',
    '凤': 'phoenix',
    '妙': 'wonderful',
    '梵': 'Sanskrit',
    '辨': 'distinguish',
    '脑': 'brain',
    '宏': 'grand',
    '棒': 'great',
    '浪': 'wave',
    '屏': 'screen',
    '辉': 'glow',
    '街': 'street',
    '纤': 'fiber',
    '狗': 'dog',
    '扇': 'fan',
    '狐': 'fox',
    '骨': 'bone',
    '玩': 'play',
    '壳': 'shell',
    '旗': 'flag',
    '妆': 'makeup',
    '冠': 'crown',
    '链': 'chain',
    '魅': 'charm',
    '勒': 'rein',
    '潮': 'tide',
    '竹': 'bamboo',
    '追': 'chase',
    '霓': 'neon',
    '祥': 'auspicious',
    '橘': 'orange',
    '烷': 'alkane',
    '忧': 'worry',
    '庞': 'huge',
    '髻': 'bun',
    '瓷': 'porcelain',
    '漠': 'desert',
    '幅': 'width',
    '耀': 'shine',
    '注': 'note',
    '意': 'meaning',
    '箍': 'hoop',
    '羽': 'feather',
    '腿': 'leg',
    '肩': 'shoulder',
    '轨': 'track',
    '袖': 'sleeve',
    '滩': 'beach',
    '塔': 'tower',
    '袋': 'bag',
    '漩': 'whirlpool',
    '涡': 'vortex',
    '窗': 'window',
    '奥': 'profound',
    '庄': 'solemn',
    '巧': 'skillful',
    '牙': 'tooth',
    '牌': 'brand',
    '夏': 'summer',
    '骑': 'ride',
    '盲': 'blind',
    '斑': 'spot',
    '迹': 'trace',
    '蛇': 'snake',
    '棕': 'brown',
    '扮': 'dress up',
    '橙': 'orange',
    '唐': 'Tang',
    '爆': 'burst',
    '仔': 'boy',
    '废': 'waste',
    '腰': 'waist',
    '栩': 'vivid',
    '狸': 'raccoon',
    '铠': 'armor',
    '噪': 'noise',
    '岛': 'island',
    '鼻': 'nose',
    '滚': 'roll',
    '码': 'code',
    '绚': 'gorgeous',
    '奶': 'milk',
    '鼠': 'mouse',
    '曝': 'expose',
    '攀': 'climb',
    '堡': 'castle',
    '杜': 'Du',
    '菲': 'fragrant',
    '矢': 'arrow',
    '衬': 'lining',
    '蛇': 'serpent',
    '塑': 'plastic',
    '侠': 'warrior',
    '蝴': 'butterfly',
    '蝶': 'butterfly',
    '似': 'like',
    '羊': 'sheep',
    '鸦': 'crow',
    '桃': 'peach',
    '怖': 'fear',
    '兽': 'beast',
    '滤': 'filter',
    '梦': 'dream',
    '叠': 'stack',
    '枝': 'branch',
    '翅': 'wing',
    '迪': 'di',
    '焰': 'flame',
    '膀': 'shoulder',
    '博': 'broad',
    '艳': 'gorgeous',
    '沫': 'foam',
    '朦': 'hazy',
    '胧': 'hazy',
    '垒': 'rampart',
    '诡': 'mysterious',
    '嘟': 'pout',
    '嘻': 'laugh',
    '哈': 'ha',
    '嘿': 'hey',
    '哟': 'yo',
    '唷': 'oh',
    '嗨': 'hi',
    '喔': 'oh',
    '哇': 'wow',
    '呜': 'woo',
    '嗯': 'hmm',
    '啦': 'la',
    '哒': 'da',
    '嗷': 'howl',
    '吼': 'roar',
    '嚎': 'howl',
    '嘶': 'hiss',
    '啸': 'whistle',
    '咆': 'roar',
    '哮': 'roar',
    '嗥': 'howl',
    '嘤': 'sob',
    '咽': 'swallow',
    '吞': 'swallow',
    '咀': 'chew',
    '嚼': 'chew',
    '啃': 'gnaw',
    '舔': 'lick',
    '吮': 'suck',
    '吐': 'spit',
    '喷': 'spray',
    '嘘': 'hush',
    '嚷': 'shout',
    '嚣': 'clamor',
    '喧': 'noisy',
    '哗': 'crash',
    '轰': 'boom',
    '隆': 'rumble',
    '咚': 'thud',
    '嘭': 'bang',
    '砰': 'bang',
    '啪': 'slap',
    '啵': 'pop',
    '嗖': 'whoosh',
    '嗡': 'buzz',
    '咻': 'swoosh',
    '飕': 'whoosh',
    '飒': 'rustle',
    '瑟': 'rustle',
    '簌': 'rustle',
    '唰': 'swish',
    '淅': 'patter',
    '沥': 'drip',
    '霈': 'rain',
    '霏': 'drizzle',
    '濛': 'misty',
    '昧': 'obscure',
    '冥': 'dark',
    '森': 'forest',
    '郁': 'dense',
    '邃': 'deep',
    '渊': 'abyss',
    '穹': 'dome',
    '苍': 'azure',
    '茫': 'vast',
    '辽': 'vast',
    '氓': 'vagrant',
    '帮': 'gang',
    '派': 'faction',
    '眩': 'dizzy',
    '揉': 'rub',
    '捏': 'pinch',
    '掐': 'pinch',
    '拧': 'twist',
    '搓': 'rub',
    '揿': 'press',
    '摁': 'press',
    '扯': 'pull',
    '拽': 'drag',
    '拖': 'drag',
    '曳': 'trail',
    '牵': 'lead',
    '携': 'carry',
    '捧': 'hold',
    '擎': 'lift',
    '扛': 'carry',
    '撑': 'support',
    '挺': 'upright',
    '竖': 'vertical',
    '硬': 'hard',
    '健': 'healthy',
    '韧': 'tough',
    '毅': 'resolute',
    '脆': 'crisp',
    '羞': 'shy',
    '怯': 'timid',
    '畏': 'fear',
    '惧': 'dread',
    '慌': 'panic',
    '忙': 'busy',
    '匆': 'hurried',
    '遽': 'sudden',
    '骤': 'sudden',
    '陡': 'steep',
    '峻': 'precipitous',
    '崎': 'rugged',
    '岖': 'rugged',
    '崚': 'rugged',
    '嶒': 'steep',
    '巉': 'cliff',
    '巅': 'summit',
    '颠': 'top',
    '尖': 'sharp',
    '锐': 'sharp',
    '锋': 'edge',
    '芒': 'radiance',
    '锷': 'edge',
    '刃': 'blade',
    '戈': 'spear',
    '枪': 'gun',
    '炮': 'cannon',
    '箭': 'arrow',
    '镖': 'dart',
    '钉': 'nail',
    '棘': 'bramble',
    '荆': 'thorn',
    '蔷': 'rose',
    '薇': 'rose',
    '蕾': 'bud',
    '苞': 'bud',
    '蕊': 'stamen',
    '萼': 'calyx',
    '梗': 'stem',
    '藤': 'vine',
    '缠': 'entangle',
    '缭': 'wind',
    '萦': 'linger',
    '绵': 'continuous',
    '伸': 'stretch',
    '舒': 'comfortable',
    '畅': 'smooth',
    '遍': 'everywhere',
    '抵': 'reach',
    '临': 'approach',
    '届': 'arrive',
    '就': 'accomplish',
    '铸': 'cast',
    '雕': 'carve',
    '琢': 'polish',
    '磨': 'grind',
    '砺': 'sharpen',
    '削': 'whittle',
    '剔': 'pick',
    '挖': 'dig',
    '掘': 'excavate',
    '凿': 'chisel',
    '钻': 'drill',
    '洞': 'hole',
    '窟': 'cave',
    '穴': 'den',
    '窝': 'nest',
    '巢': 'nest',
    '窠': 'nest',
    '坑': 'pit',
    '凹': 'concave',
    '陷': 'sink',
    '塌': 'collapse',
    '垮': 'collapse',
    '坍': 'collapse',
    '摧': 'destroy',
    '毁': 'ruin',
    '痛': 'pain',
    '疼': 'ache',
    '麻': 'numb',
    '痒': 'itchy',
    '痹': 'numb',
    '僵': 'stiff',
    '滞': 'stagnant',
    '钝': 'blunt',
    '癫': 'crazy',
    '疯': 'insane',
    '怔': 'stupefied',
    '愣': 'stunned',
    '徐': 'slowly',
    '耽': 'delay',
    '搁': 'shelve',
    '陈': 'display',
    '蜿': 'winding',
    '迂': 'roundabout',
    '迴': 'circle',
    '徊': 'wander',
    '返': 'return',
    '恢': 'recover',
    '愈': 'heal',
    '救': 'save',
    '援': 'rescue',
    '扶': 'support',
    '御': 'resist',
    '挡': 'block',
    '遏': 'stop',
    '抑': 'suppress',
    '栓': 'fasten',
    '拴': 'tether',
    '羁': 'restrain',
    '禁': 'prohibit',
    '锁': 'lock',
    '塞': 'plug',
    '堵': 'block',
    '截': 'cut off',
    '碎': 'shatter',
    '屑': 'crumb',
    '渣': 'residue',
    '涎': 'saliva',
    '汁': 'juice',
    '浆': 'pulp',
    '糊': 'paste',
    '糕': 'cake',
    '饺': 'dumpling',
    '馒': 'steamed bun',
    '馍': 'bun',
    '酥': 'crispy',
    '爽': 'crisp',
    '糯': 'glutinous',
    '软': 'soft',
    '稀': 'dilute',
    '淡': 'light',
    '稠': 'dense',
    '坠': 'drop',
    '吊': 'hang',
    '挂': 'hang',
    '陨': 'fall',
    '沦': 'fall',
    '堕': 'fall',
    '跌': 'fall',
    '摔': 'fall',
    '没': 'submerge',
    '淹': 'flood',
    '溺': 'drown',
    '浸': 'soak',
    '渍': 'stain',
    '沾': 'contaminate',
    '污': 'dirty',
    '浊': 'turbid',
    '浑': 'turbid',
    '楞': 'stupefied',
    # Additional common ones
    '娘': 'mother',
    '爹': 'father',
    '爸': 'dad',
    '妈': 'mom',
    '姐': 'sister',
    '哥': 'brother',
    '弟': 'brother',
    '妹': 'sister',
    '叔': 'uncle',
    '姨': 'aunt',
    '舅': 'uncle',
    '姑': 'aunt',
    '婶': 'aunt',
    '嫂': 'sister-in-law',
    '媳': 'daughter-in-law',
    '婿': 'son-in-law',
    '孙': 'grandchild',
    '孙': 'grandson',
    '侄': 'nephew',
    '甥': 'nephew',
    '婴': 'infant',
    '童': 'child',
    '仙': 'fairy',
    '佛': 'Buddha',
    '神': 'god',
    '鬼': 'ghost',
    '妖': 'demon',
    '巫': 'witch',
    '仙': 'immortal',
    '龙': 'dragon',
    '凤': 'phoenix',
    '虎': 'tiger',
    '狮': 'lion',
    '豹': 'leopard',
    '狼': 'wolf',
    '熊': 'bear',
    '鹿': 'deer',
    '象': 'elephant',
    '猴': 'monkey',
    '猿': 'ape',
    '猩': 'orangutan',
    '鹰': 'eagle',
    '鹤': 'crane',
    '鸽': 'pigeon',
    '鹅': 'goose',
    '鸭': 'duck',
    '鹦': 'parrot',
    '鹉': 'parrot',
    '乌': 'crow',
    '鸦': 'raven',
    '蝙': 'bat',
    '蝠': 'bat',
    '蝶': 'butterfly',
    '蜂': 'bee',
    '蜜': 'honey',
    '蚁': 'ant',
    '蜘': 'spider',
    '蛛': 'spider',
    '蝎': 'scorpion',
    '蟹': 'crab',
    '虾': 'shrimp',
    '蟆': 'toad',
    '蛙': 'frog',
    '龟': 'turtle',
    '鳖': 'turtle',
    '鳄': 'crocodile',
    '鲸': 'whale',
    '鲨': 'shark',
    '豚': 'dolphin',
    '鳗': 'eel',
    '鳟': 'trout',
    '鲤': 'carp',
    '鲫': 'crucian',
    '鲈': 'bass',
    '鳕': 'cod',
    '鲑': 'salmon',
    '鳅': 'loach',
    '贝': 'shell',
    '螺': 'snail',
    '蚌': 'clam',
    '蛤': 'clam',
    '蛎': 'oyster',
    '扇': 'scallop',
    '蟹': 'crab',
    '虾': 'shrimp',
    '蜗': 'snail',
}

def translate_prompt(prompt):
    """Translate Chinese characters in a prompt to English"""
    result = prompt
    for chinese, english in char_translations.items():
        if english:
            result = result.replace(chinese, english)
    return result

def count_chinese_chars(text):
    """Count Chinese characters in text"""
    return len(re.findall(r'[\u4e00-\u9fff]', text))

print("Loading image_prompt.json...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

print("\nPass 6: Comprehensive cleanup...")
translated_count = 0
total_before = 0
total_after = 0

for category in json_data.get('data', []):
    for image_item in category.get('images', []):
        if 'prompt' in image_item:
            original = image_item['prompt']
            chinese_before = count_chinese_chars(original)
            total_before += chinese_before
            
            if chinese_before > 0:
                translated = translate_prompt(original)
                chinese_after = count_chinese_chars(translated)
                total_after += chinese_after
                
                if chinese_after < chinese_before:
                    image_item['prompt'] = translated
                    translated_count += 1

print(f"\nSaving updated file...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f"\n✅ Pass 6 complete!")
print(f"Modified {translated_count} prompts")
print(f"Chinese characters: {total_before} → {total_after}")
if total_before > 0:
    reduction_pct = ((total_before - total_after) / total_before * 100)
    print(f"Removed: {total_before - total_after} characters ({reduction_pct:.1f}%)")
    print(f"\n📊 Translation Progress Summary:")
    print(f"   Remaining: {total_after} Chinese characters")
    print(f"   Status: {'✅ Substantially complete' if total_after < 2000 else '🔄 Continue translating'}")
