#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive translation script for lens.js
Translates all remaining Chinese comments to English
"""

import re

# Comprehensive translation dictionary
translations = {
    # Function and method related
    '调用': 'call',
    '如果': 'if',
    '否则': 'else',  
    '返回': 'return',
    '传入': 'pass in',
    '传递': 'pass',
    '节点': 'node',
    '元素': 'element',
    '属性': 'attribute',
    '内容': 'content',
    '文本': 'text',
    '图片': 'image',
    '链接': 'link',
    '标题': 'heading',
    '段落': 'paragraph',
    '列表': 'list',
    '表格': 'table',
    '代码': 'code',
    '样式': 'style',
    '类名': 'class name',
    '标签': 'tag',
    '子节点': 'child node',
    '父节点': 'parent node',
    '祖先节点': 'ancestor node',
    '后代节点': 'descendant node',
    '兄弟节点': 'sibling node',
    '当前': 'current',
    '目标': 'target',
    '源': 'source',
    '结果': 'result',
    '数组': 'array',
    '对象': 'object',
    '函数': 'function',
    '方法': 'method',
    '参数': 'parameter',
    '变量': 'variable',
    '常量': 'constant',
    '配置': 'configuration',
    '选项': 'option',
    '设置': 'setting',
    '默认': 'default',
    '可选': 'optional',
    '必需': 'required',
    '有效': 'valid',
    '无效': 'invalid',
    '为空': 'empty',
    '非空': 'non-empty',
    '存在': 'exists',
    '不存在': 'does not exist',
    '包含': 'contains',
    '匹配': 'match',
    '替换': 'replace',
    '移除': 'remove',
    '删除': 'delete',
    '添加': 'add',
    '插入': 'insert',
    '更新': 'update',
    '修改': 'modify',
    '查找': 'find',
    '搜索': 'search',
    '过滤': 'filter',
    '排序': 'sort',
    '遍历': 'traverse',
    '迭代': 'iterate',
    '递归': 'recursive',
    '循环': 'loop',
    '条件': 'condition',
    '分支': 'branch',
    '判断': 'determine',
    '检查': 'check',
    '验证': 'validate',
    '测试': 'test',
    '断言': 'assert',
    '错误': 'error',
    '异常': 'exception',
    '警告': 'warning',
    '信息': 'info',
    '日志': 'log',
    '调试': 'debug',
    '输出': 'output',
    '打印': 'print',
    '格式化': 'format',
    '解析': 'parse',
    '序列化': 'serialize',
    '反序列化': 'deserialize',
    '编码': 'encode',
    '解码': 'decode',
    '转义': 'escape',
    '去转义': 'unescape',
    '截取': 'truncate',
    '拼接': 'concatenate',
    '分割': 'split',
    '合并': 'merge',
    '连接': 'join',
    '清理': 'clean',
    '修剪': 'trim',
    '规范化': 'normalize',
    '标准化': 'standardize',
    '优化': 'optimize',
    '性能': 'performance',
    '效率': 'efficiency',
    '速度': 'speed',
    '内存': 'memory',
    '资源': 'resource',
    '缓存': 'cache',
    '延迟': 'delay',
    '异步': 'async',
    '同步': 'sync',
    '回调': 'callback',
    '承诺': 'promise',
    '事件': 'event',
    '监听': 'listen',
    '触发': 'trigger',
    '执行': 'execute',
    '运行': 'run',
    '开始': 'start',
    '结束': 'end',
    '完成': 'complete',
    '终止': 'terminate',
    '中断': 'interrupt',
    '暂停': 'pause',
    '继续': 'continue',
    '重试': 'retry',
    '重置': 'reset',
    '初始化': 'initialize',
    '销毁': 'destroy',
    '释放': 'release',
    '占用': 'occupy',
    '使用': 'use',
    '应用': 'apply',
    '生效': 'take effect',
    '失效': 'become invalid',
    '启用': 'enable',
    '禁用': 'disable',
    '开关': 'toggle',
    '显示': 'show',
    '隐藏': 'hide',
    '可见': 'visible',
    '不可见': 'invisible',
    '透明': 'transparent',
    '不透明': 'opaque',
    '宽度': 'width',
    '高度': 'height',
    '尺寸': 'dimension',
    '大小': 'size',
    '位置': 'position',
    '坐标': 'coordinate',
    '偏移': 'offset',
    '边距': 'margin',
    '内边距': 'padding',
    '边框': 'border',
    '背景': 'background',
    '颜色': 'color',
    '字体': 'font',
    '字号': 'font size',
    '粗体': 'bold',
    '斜体': 'italic',
    '下划线': 'underline',
    '删除线': 'strikethrough',
    '对齐': 'align',
    '居中': 'center',
    '左对齐': 'left align',
    '右对齐': 'right align',
    '两端对齐': 'justify',
    '换行': 'line break',
    '空格': 'space',
    '制表符': 'tab',
    '缩进': 'indent',
    '行高': 'line height',
    '字间距': 'letter spacing',
    '词间距': 'word spacing',
    '页面': 'page',
    '文档': 'document',
    '视口': 'viewport',
    '窗口': 'window',
    '浏览器': 'browser',
    '滚动': 'scroll',
    '点击': 'click',
    '双击': 'double click',
    '右键': 'right click',
    '悬停': 'hover',
    '拖动': 'drag',
    '拖拽': 'drag and drop',
    '输入': 'input',
    '提交': 'submit',
    '重置': 'reset',
    '选择': 'select',
    '取消选择': 'deselect',
    '全选': 'select all',
    '复制': 'copy',
    '粘贴': 'paste',
    '剪切': 'cut',
    '撤销': 'undo',
    '重做': 'redo',
    '保存': 'save',
    '加载': 'load',
    '刷新': 'refresh',
    '重新加载': 'reload',
    '跳转': 'navigate',
    '重定向': 'redirect',
    '前进': 'forward',
    '后退': 'backward',
    '首页': 'home',
    '末页': 'end',
    '上一页': 'previous',
    '下一页': 'next',
    '第一个': 'first',
    '最后一个': 'last',
    '上一个': 'previous',
    '下一个': 'next',
    '索引': 'index',
    '序号': 'sequence',
    '编号': 'number',
    '计数': 'count',
    '总数': 'total',
    '数量': 'quantity',
    '长度': 'length',
    '最大值': 'maximum',
    '最小值': 'minimum',
    '平均值': 'average',
    '总和': 'sum',
    '差值': 'difference',
    '乘积': 'product',
    '商': 'quotient',
    '余数': 'remainder',
    '百分比': 'percentage',
    '比例': 'ratio',
    '分数': 'fraction',
    '小数': 'decimal',
    '整数': 'integer',
    '浮点数': 'float',
    '布尔值': 'boolean',
    '真': 'true',
    '假': 'false',
    '空值': 'null',
    '未定义': 'undefined',
    '正则表达式': 'regular expression',
    '正则': 'regex',
    '模式': 'pattern',
    '通配符': 'wildcard',
    '特殊字符': 'special character',
    '转义字符': 'escape character',
    '分隔符': 'separator',
    '定界符': 'delimiter',
    '注释': 'comment',
    '文档注释': 'documentation comment',
    '单行注释': 'single line comment',
    '多行注释': 'multi-line comment',
    '块注释': 'block comment',
    '说明': 'description',
    '描述': 'description',
    '备注': 'note',
    '提示': 'hint',
    '示例': 'example',
    '用法': 'usage',
    '语法': 'syntax',
    '规则': 'rule',
    '约束': 'constraint',
    '限制': 'restriction',
    '要求': 'requirement',
    '建议': 'suggestion',
    '推荐': 'recommended',
    '最佳实践': 'best practice',
    '注意': 'note',
    '警告': 'warning',
    '危险': 'danger',
    '重要': 'important',
    '关键': 'key',
    '核心': 'core',
    '主要': 'main',
    '次要': 'secondary',
    '可选': 'optional',
    '额外': 'additional',
    '补充': 'supplementary',
    '扩展': 'extension',
    '增强': 'enhancement',
    '改进': 'improvement',
    '修复': 'fix',
    '修正': 'correction',
    '更正': 'rectification',
    '调整': 'adjustment',
    '微调': 'fine-tune',
    '定制': 'customize',
    '自定义': 'custom',
    '预设': 'preset',
    '模板': 'template',
    '原型': 'prototype',
    '实例': 'instance',
    '副本': 'copy',
    '克隆': 'clone',
    '引用': 'reference',
    '指针': 'pointer',
    '地址': 'address',
    '路径': 'path',
    '文件名': 'filename',
    '扩展名': 'extension',
    '协议': 'protocol',
    '域名': 'domain',
    '主机': 'host',
    '端口': 'port',
    '查询': 'query',
    '哈希': 'hash',
    '片段': 'fragment',
    '锚点': 'anchor',
    '书签': 'bookmark',
    '历史': 'history',
    '会话': 'session',
    '存储': 'storage',
    '本地': 'local',
    '远程': 'remote',
    '服务器': 'server',
    '客户端': 'client',
    '请求': 'request',
    '响应': 'response',
    '状态码': 'status code',
    '头部': 'header',
    '主体': 'body',
    '载荷': 'payload',
    '数据': 'data',
    '元数据': 'metadata',
    '类型': 'type',
    '格式': 'format',
    '版本': 'version',
    '作者': 'author',
    '日期': 'date',
    '时间': 'time',
    '时间戳': 'timestamp',
    '过期': 'expire',
    '有效期': 'validity period',
    '生命周期': 'lifecycle',
    '创建': 'create',
    '修改': 'modify',
    '更新': 'update',
    '删除': 'delete',
    '访问': 'access',
    '读取': 'read',
    '写入': 'write',
    '追加': 'append',
    '覆盖': 'overwrite',
    '权限': 'permission',
    '所有者': 'owner',
    '组': 'group',
    '用户': 'user',
    '角色': 'role',
    '身份': 'identity',
    '认证': 'authentication',
    '授权': 'authorization',
    '令牌': 'token',
    '密钥': 'key',
    '密码': 'password',
    '签名': 'signature',
    '加密': 'encrypt',
    '解密': 'decrypt',
    '哈希': 'hash',
    '校验': 'checksum',
    '验证码': 'verification code',
    '安全': 'security',
    '隐私': 'privacy',
    '保护': 'protection',
    '过滤': 'filter',
    '净化': 'sanitize',
    '转换': 'transform',
    '映射': 'map',
    '规约': 'reduce',
    '展开': 'flatten',
    '扁平化': 'flatten',
    '分组': 'group',
    '分类': 'categorize',
    '排序': 'sort',
    '顺序': 'order',
    '升序': 'ascending',
    '降序': 'descending',
    '倒序': 'reverse',
    '乱序': 'shuffle',
    '随机': 'random',
    '唯一': 'unique',
    '去重': 'deduplicate',
    '交集': 'intersection',
    '并集': 'union',
    '差集': 'difference',
    '补集': 'complement',
    '子集': 'subset',
    '超集': 'superset',
    '空集': 'empty set',
    '集合': 'set',
    '队列': 'queue',
    '栈': 'stack',
    '堆': 'heap',
    '树': 'tree',
    '图': 'graph',
    '节点': 'node',
    '边': 'edge',
    '权重': 'weight',
    '深度': 'depth',
    '层级': 'level',
    '根': 'root',
    '叶子': 'leaf',
    '分支': 'branch',
    '路径': 'path',
    '遍历': 'traverse',
    '搜索': 'search',
    '查询': 'query',
    '插入': 'insert',
    '删除': 'delete',
    '更新': 'update',
    '平衡': 'balance',
    '排序': 'sort',
    '算法': 'algorithm',
    '复杂度': 'complexity',
    '时间复杂度': 'time complexity',
    '空间复杂度': 'space complexity',
    '优化': 'optimization',
    '性能': 'performance',
}

def translate_file(filepath):
    """Translate Chinese strings in file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Apply translations
    for chinese, english in translations.items():
        content = content.replace(chinese, english)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    # Count remaining
    import re
    remaining = len(re.findall(r'[\u4e00-\u9fff]+', content))
    print(f"Translation complete. Remaining Chinese characters: {remaining}")

if __name__ == '__main__':
    filepath = r'c:\Users\kubew\magic\backend\be-delightful\delightful_use\js\lens.js'
    translate_file(filepath)
