#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

# Extended Chinese to English translation dictionary - focusing on common characters
translations = {
    # Previously missing common characters
    '清': 'clear',
    '男子': 'man',
    '戴': 'wearing',
    '眼镜': 'glasses',
    '镜片': 'lens',
    '描': 'describe',
    '绘': 'draw',
    '风景': 'landscape',
    '景色': 'scenery',
    '溢': 'overflow',
    '来': 'come',
    '自': 'from',
    '视角': 'perspective',
    '看': 'look',
    '融入': 'blend into',
    '速': 'speed',
    '公路': 'highway',
    '元素': 'elements',
    '蓝': 'blue',
    '绿': 'green',
    '点': 'point',
    '缀': 'embellish',
    '红': 'red',
    '黄': 'yellow',
    '植物': 'plants',
    '云': 'cloud',
    '凸显': 'highlight',
    '未来': 'future',
    '科技': 'technology',
    '感': 'feeling',
    '视觉': 'visual',
    '冲击': 'impact',
    '突然': 'suddenly',
    '角色': 'character',
    '抠': 'matting',
    '像': 'image',
    '兴': 'excited',
    '跳': 'jump',
    '起来': 'up',
    '梦幻': 'dreamy',
    '欢乐': 'joyful',
    '夸张': 'exaggerated',
    '节日': 'festival',
    '火爆': 'hot',
    '旅游': 'travel',
    '多彩': 'colorful',
    '世界': 'world',
    '主要': 'main',
    '打卡': 'check in',
    '地': 'place',
    '剪影': 'silhouette',
    '波普': 'pop art',
    '风格': 'style',
    '创意': 'creative',
    '拼贴': 'collage',
    '撕纸': 'torn paper',
    '描边': 'outline',
    '女孩': 'girl',
    '高': 'high',
    '烈': 'intense',
    '色': 'color',
    '对比': 'contrast',
    '创造': 'create',
    '令人': 'making people',
    '震撼': 'stunning',
    '画面': 'scene',
    '孤': 'alone',
    '悬': 'hanging',
    '无尽': 'endless',
    '深蓝': 'deep blue',
    '纯黑': 'pure black',
    '仅': 'only',
    '淡': 'light',
    '轻': 'lightly',
    '绕': 'around',
    '营造': 'create',
    '超脱': 'transcend',
    '尘世': 'worldly',
    '静': 'quiet',
    '美': 'beauty',
    '份': 'portion',
    '极简': 'minimalist',
    '不仅': 'not only',
    '千里': 'thousand miles',
    '寄': 'send',
    '相思': 'longing',
    '主题': 'theme',
    '深刻': 'profound',
    '诠释': 'interpretation',
    '更是': 'moreover',
    '艺术': 'art',
    '极致': 'ultimate',
    '追求': 'pursuit',
    '体现': 'embody',
    '让': 'let',
    '简洁': 'concise',
    '强': 'strong',
    '情感': 'emotion',
    '共鸣': 'resonance',
    '巨匠': 'master',
    '操刀': 'created',
    '明月': 'bright moon',
    '核心': 'core',
    '通过': 'through',
    '构图': 'composition',
    '出': 'out',
    '中': 'in',
    '周围': 'around',
    '或': 'or',
    '有': 'have',
    '几缕': 'several wisps',
    '种': 'kind',
    '这': 'this',
    '对': 'to',
    '手持': 'holding',
    '巨大': 'giant',
    '桂花': 'osmanthus',
    '雕': 'carving',
    '质感': 'texture',
    '表现': 'express',
    '指甲': 'nails',
    '图案': 'pattern',
    '工艺': 'craft',
    '微': 'micro',
    '花瓣': 'petals',
    '如同': 'like',
    '半透明': 'translucent',
    '玉': 'jade',
    '片': 'piece',
    '花蕊': 'stamen',
    '散发': 'emit',
    '金色': 'golden',
    '光芒': 'radiance',
    '镶嵌': 'inlaid',
    '金粉': 'gold powder',
    '背景': 'background',
    '模糊': 'blurred',
    '月宫': 'moon palace',
    '轮廓': 'outline',
    '只': 'only',
    '能': 'can',
    '到': 'to',
    '些': 'some',
    '琉璃': 'glaze',
    '宫墙': 'palace wall',
    '角': 'corner',
    '云雾': 'mist',
    '细腻': 'delicate',
    '肌肤': 'skin',
    '晶莹': 'crystal',
    '冷色调': 'cold tones',
    '主': 'main',
    '冰蓝': 'ice blue',
    '金黄': 'golden',
    '相衬': 'complement',
    '材质': 'material',
    '渲染器': 'renderer',
    '唯美': 'aesthetic',
    '神话': 'mythology',
    '结合': 'combined',
    '空白': 'blank',
    '镜头': 'lens',
    '侧光': 'side light',
    '模拟': 'simulate',
    '从': 'from',
    '侧面': 'side',
    '洒': 'pour',
    '光晕': 'halo',
    '海报': 'poster',
    '设计': 'design',
    '为': 'as',
    '由': 'by',
    '位': 'located',
    '于': 'at',
    '正': 'right',
    '中心': 'center',
    '虚化': 'blur',
    '黑色': 'black',
    '炸开': 'explode',
    '金黄色': 'golden',
    '透明': 'transparent',
    '渐变': 'gradient',
    '油脂': 'oil',
    '空': 'air',
    '漂浮': 'floating',
    '鲜美': 'fresh',
    '叶子': 'leaves',
    '小': 'small',
    '番茄': 'tomato',
    '灯笼椒': 'bell pepper',
    '深': 'deep',
    '全局': 'global',
    '光照': 'lighting',
    '影棚': 'studio',
    '打光': 'lighting',
    '广告': 'advertising',
    '大师': 'master',
    '作品': 'work',
    '简约': 'simple',
    '美观': 'beautiful',
    '铁': 'iron',
    '凹凸': 'bumpy',
    '反光': 'reflective',
    '镜面': 'mirror',
    '桌子': 'table',
    '圆润': 'rounded',
    '饱满': 'full',
    '艺术字': 'artistic text',
    '标题': 'title',
    '字体': 'font',
    '不规则': 'irregular',
    '排列': 'arrangement',
    '大小': 'size',
    '变化': 'change',
    '基调': 'tone',
    '变暗': 'darken',
    '偏': 'lean',
    '吃光': 'overexposed',
    '高级': 'advanced',
    '仰角': 'low angle',
    '低': 'low',
    '机位': 'camera position',
    '虚拟': 'virtual',
    '躺': 'lying',
    '猫': 'cat',
    '头': 'head',
    '圆形': 'round',
    '月': 'moon',
    '光影': 'light and shadow',
    '孤独': 'lonely',
    '治愈': 'healing',
    '虚无': 'void',
    '负空间': 'negative space',
    '食品': 'food',
    '汉堡包': 'hamburger',
    '里面': 'inside',
    '夹': 'sandwich',
    '鲜嫩': 'fresh',
    '蔬菜': 'vegetables',
    '牛排': 'steak',
    '超': 'ultra',
    '细节': 'details',
    '我': 'I',
    '手拉手': 'hand in hand',
    '沿': 'along',
    '绳梯': 'rope ladder',
    '爬': 'climb',
    '上': 'on',
    '月球': 'moon',
    '个': 'a',
    '场景': 'scenario',
    '宇航员': 'astronaut',
    '简单': 'simple',
    '攀爬': 'climbing',
    '垂直': 'vertical',
    '梯子': 'ladder',
    '关键': 'key',
    '点是': 'point is',
    '上升': 'rise',
    '登山者': 'climber',
    '之间': 'between',
    '广阔': 'vast',
    '空间感': 'sense of space',
    '唤起': 'evoke',
    '决心': 'determination',
    '敬畏': 'awe',
    '地球': 'earth',
    '唯一': 'only',
    '连接': 'connection',
    '强调': 'emphasize',
    '光滑': 'smooth',
    '整洁': 'neat',
    '美学': 'aesthetics',
    '格式': 'format',
    '配色': 'color scheme',
    '广袤': 'vast',
    '草原': 'grassland',
    '辆': 'vehicle',
    '小巧': 'compact',
    '绿色': 'green',
    '巴士': 'bus',
    '行驶': 'traveling',
    '天空': 'sky',
    '湛蓝': 'azure',
    '无云': 'cloudless',
    '阳光': 'sunshine',
    '明媚': 'bright',
    '看起来': 'looks like',
    '正在': 'currently',
    '前往': 'heading to',
    '某个': 'some',
    '遥远': 'distant',
    '目的地': 'destination',
    '也许': 'maybe',
    '未知': 'unknown',
    '冒险': 'adventure',
    '之旅': 'journey',
    '它': 'it',
    '穿越': 'crossing',
    '起伏': 'rolling',
    '山丘': 'hills',
    '留下': 'leaving',
    '道': 'path',
    '车轮': 'wheel',
    '印迹': 'tracks',
    '远处': 'distance',
    '几只': 'several',
    '牛羊': 'cattle',
    '悠闲': 'leisurely',
    '吃草': 'grazing',
    '它们': 'they',
    '毫不': 'not at all',
    '在意': 'care',
    '整个': 'whole',
    '充满': 'full of',
    '宁静': 'serene',
    '自由': 'free',
    '气息': 'atmosphere',
    '想起': 'recall',
    '那些': 'those',
    '远离': 'away from',
    '城市': 'city',
    '喧嚣': 'hustle',
    '日子': 'days',
    '夜幕': 'night',
    '街道': 'street',
    '身影': 'figure',
    '缓缓': 'slowly',
    '行走': 'walking',
    '失焦': 'defocus',
    '捕捉': 'capture',
    '融合': 'fusion',
    '街拍': 'street photography',
    '韵味': 'charm',
    '孤寂': 'solitary',
    '氛围': 'atmosphere',
    '采用': 'adopt',
    '抽象': 'abstract',
    '白': 'white',
    '深紫': 'deep purple',
    '构建': 'build',
    '空灵': 'ethereal',
    '梦境': 'dream',
    '自然光': 'natural light',
    '数字': 'digital',
    '技术': 'technology',
    '巧妙': 'clever',
    '造成': 'create',
    '发光': 'glowing',
    '彩虹': 'rainbow',
    '增添': 'add',
    '抹': 'touch',
    '夜晚': 'night',
    '神秘': 'mysterious',
    '迷离': 'hazy',
}

def translate_prompt(prompt):
    """Translate Chinese characters in a prompt to English"""
    result = prompt
    # Sort by length (longest first) to handle multi-character phrases before single characters
    for chinese, english in sorted(translations.items(), key=lambda x: -len(x[0])):
        result = result.replace(chinese, english)
    return result

def count_chinese_chars(text):
    """Count Chinese characters in text"""
    return len(re.findall(r'[\u4e00-\u9fff]', text))

# Load the JSON file
print("Loading image_prompt.json...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

# Process prompts
print("\nTranslating prompts with extended dictionary...")
translated_count = 0
total_before = 0
total_after = 0

for category in json_data.get('data', []):
    for image_item in category.get('images', []):
        if 'prompt' in image_item:
            original = image_item['prompt']
            chinese_before = count_chinese_chars(original)
            total_before += chinese_before
            
            if chinese_before > 0:
                translated = translate_prompt(original)
                chinese_after = count_chinese_chars(translated)
                total_after += chinese_after
                
                if chinese_after < chinese_before:
                    image_item['prompt'] = translated
                    translated_count += 1
                    reduction = chinese_before - chinese_after
                    if translated_count <= 10:  # Show first 10 for monitoring
                        print(f"✓ Prompt {translated_count}: {chinese_before} → {chinese_after} chars (reduced {reduction})")

# Save the updated file
print(f"\nSaving updated file...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f"\n✓ Complete!")
print(f"Translated {translated_count} prompts")
print(f"Total Chinese characters: {total_before} → {total_after}")
print(f"Reduction: {total_before - total_after} characters ({((total_before - total_after) / total_before * 100):.1f}%)")
