#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

# Targeted translations for most frequent remaining characters
char_translations = {
    # Top frequency characters from analysis
    '饰': 'decoration',
    '幻': 'illusion',
    '装': 'outfit',
    '暗': 'dark',
    '漫': 'diffuse',
    '丽': 'beautiful',
    '卡': 'card',
    '雾': 'fog',
    '透': 'transparent',
    '茸': 'fluffy',
    '焦': 'focal',
    '童': 'child',
    '飘': 'float',
    '巨': 'giant',
    '饼': 'cake',
    '兔': 'rabbit',
    '奇': 'strange',
    '颗': 'grain',
    '佳': 'good',
    '耳': 'ear',
    '帽': 'hat',
    '镜': 'mirror',
    '男': 'man',
    '怪': 'monster',
    '肖': 'portrait',
    '闪': 'flash',
    '暖': 'warm',
    '迷': 'lost',
    '不': 'not',
    '仙': 'fairy',
    '墨': 'ink',
    '版': 'version',
    '展': 'unfold',
    '开': 'open',
    '逼': 'realistic',
    '纹': 'pattern',
    '裙': 'skirt',
    '舞': 'dance',
    '魔': 'magic',
    '姿': 'posture',
    '珠': 'pearl',
    '虚': 'virtual',
    '笑': 'smile',
    '咪': 'squint',
    '诞': 'birth',
    '佛': 'Buddha',
    '宇': 'universe',
    '宝': 'treasure',
    '筑': 'build',
    '拍': 'shoot',
    '朵': 'flower',
    '袍': 'robe',
    '乎': '',
    '晕': 'dizzy',
    '娃': 'doll',
    '缘': 'edge',
    '纱': 'gauze',
    '雪': 'snow',
    '典': 'classic',
    '盒': 'box',
    '仿': 'imitate',
    '绣': 'embroidery',
    '宙': 'cosmos',
    '侧': 'side',
    '酷': 'cool',
    '晰': 'clear',
    '悟': 'enlighten',
    '弥': 'fill',
    '幽': 'quiet',
    '胺': 'amine',
    '涂': 'paint',
    '拟': 'simulate',
    '泡': 'bubble',
    '炫': 'dazzle',
    '勾': 'hook',
    '圈': 'circle',
    '惊': 'surprise',
    '饱': 'full',
    '郁': 'lush',
    '虹': 'rainbow',
    '壁': 'wall',
    '搭': 'match',
    '摆': 'place',
    '禅': 'zen',
    '熊': 'bear',
    '裤': 'pants',
    '宫': 'palace',
    '鸟': 'bird',
    '鞋': 'shoes',
    '胖': 'fat',
    '刺': 'thorn',
    '抱': 'hug',
    '渺': 'tiny',
    '泼': 'splash',
    '符': 'symbol',
    '嘴': 'mouth',
    '盔': 'helmet',
    '刷': 'brush',
    '桌': 'table',
    '杯': 'cup',
    '漆': 'lacquer',
    '托': 'tray',
    '犹': 'like',
    '镀': 'plated',
    '折': 'refraction',
    '拼': 'assemble',
    '弹': 'elastic',
    '泊': 'lake',
    '索': 'explore',
    '檐': 'eaves',
    '玫': 'rose',
    '瑰': 'rose',
    '蝉': 'cicada',
    '翼': 'wing',
    '脉': 'vein',
    '络': 'network',
    '鎏': 'gilded',
    '绢': 'silk',
    '障': 'barrier',
    '矢': 'arrow',
    '衬': 'lining',
    '檀': 'sandalwood',
    '柔': 'soft',
    '绒': 'velvet',
    '蓬': 'fluffy',
    '馨': 'fragrant',
    '谐': 'harmony',
    '韵': 'rhythm',
    '趴': 'lie',
    '躺': 'recline',
    '坠': 'fall',
    '悬': 'hang',
    '凝': 'condense',
    '霜': 'frost',
    '霞': 'sunset glow',
    '曦': 'dawn',
    '晨': 'morning',
    '暮': 'dusk',
    '昏': 'dim',
    '瞳': 'pupil',
    '睫': 'eyelash',
    '唇': 'lips',
    '颊': 'cheek',
    '鬓': 'temple',
    '眉': 'eyebrow',
    '肌': 'muscle',
    '肤': 'skin',
    '肢': 'limb',
    '躯': 'body',
    '驱': 'drive',
    '缓': 'slow',
    '匀': 'even',
    '稳': 'stable',
    '震': 'shake',
    '颤': 'tremble',
    '摇': 'sway',
    '晃': 'shake',
    '荡': 'swing',
    '漂': 'drift',
    '浮': 'float',
    '沉': 'sink',
    '潜': 'dive',
    '涌': 'surge',
    '溅': 'splash',
    '滴': 'drip',
    '淋': 'drench',
    '湿': 'wet',
    '润': 'moist',
    '燥': 'dry',
    '涩': 'astringent',
    '滑': 'smooth',
    '糙': 'rough',
    '粗': 'coarse',
    '茂': 'lush',
    '盛': 'flourish',
    '繁': 'prosperous',
    '密': 'dense',
    '疏': 'sparse',
    '稀': 'rare',
    '厚': 'thick',
    '薄': 'thin',
    '窄': 'narrow',
    '宽': 'wide',
    '阔': 'broad',
    '遥': 'distant',
    '邈': 'remote',
    '旷': 'vast',
    '垠': 'boundary',
    '涯': 'edge',
    '畔': 'bank',
    '岸': 'shore',
    '滨': 'waterside',
    '湾': 'bay',
    '峡': 'gorge',
    '谷': 'valley',
    '壑': 'ravine',
    '峰': 'peak',
    '岭': 'ridge',
    '坡': 'slope',
    '丘': 'hill',
    '陵': 'mound',
    '岩': 'rock',
    '峭': 'steep',
    '巍': 'lofty',
    '峨': 'towering',
    '嵯': 'rugged',
    '岱': 'mount',
    '岳': 'mountain',
    '崇': 'high',
    '秀': 'elegant',
    '奇': 'wonderful',
    '伟': 'great',
    '壮': 'magnificent',
    '观': 'sight',
    '瞻': 'gaze',
    '眺': 'overlook',
    '览': 'view',
    '瞰': 'overlook',
    '俯': 'bow',
    '仰': 'look up',
    '睹': 'see',
    '盯': 'stare',
    '凝': 'gaze',
    '视': 'view',
    '瞥': 'glimpse',
    '瞧': 'look',
    '瞄': 'aim',
    '瞅': 'glance',
    '瞪': 'stare',
    '瞻': 'look',
    '瞿': 'surprised',
    '矍': 'vigorous',
    '睁': 'open',
    '闭': 'close',
    '眨': 'blink',
    '眯': 'squint',
    '瞌': 'drowsy',
    '睏': 'sleepy',
    '倦': 'tired',
    '惫': 'exhausted',
    '乏': 'weary',
    '懒': 'lazy',
    '怠': 'idle',
    '慵': 'languid',
    '娇': 'delicate',
    '柔': 'gentle',
    '嫩': 'tender',
    '娴': 'graceful',
    '雅': 'elegant',
    '芳': 'fragrant',
    '艳': 'gorgeous',
    '俏': 'pretty',
    '俊': 'handsome',
    '靓': 'beautiful',
    '帅': 'handsome',
    '丑': 'ugly',
    '拙': 'clumsy',
    '笨': 'stupid',
    '愚': 'foolish',
    '蠢': 'dumb',
    '呆': 'dull',
    '傻': 'silly',
    '痴': 'crazy',
    '狂': 'mad',
    '野': 'wild',
    '猖': 'rampant',
    '肆': 'wanton',
    '恣': 'unrestrained',
    '纵': 'indulge',
    '放': 'release',
    '縱': 'vertical',
    '横': 'horizontal',
    '斜': 'slant',
    '歪': 'crooked',
    '扭': 'twist',
    '曲': 'curve',
    '弯': 'bend',
    '钩': 'hook',
    '拐': 'turn',
    '蜿': 'winding',
    '蜒': 'meandering',
    '峦': 'mountain range',
    '簇': 'cluster',
    '丛': 'thicket',
    '拥': 'embrace',
    '挤': 'crowd',
    '挨': 'close',
    '靠': 'lean',
    '贴': 'stick',
    '附': 'attach',
    '缚': 'bind',
    '束': 'tie',
    '扎': 'fasten',
    '捆': 'bundle',
    '绑': 'bind',
    '缠': 'wrap',
    '绕': 'wind',
    '盘': 'coil',
    '旋': 'spiral',
    '卷': 'roll',
    '裹': 'wrap',
    '包': 'package',
    '笼': 'cage',
    '罩': 'cover',
    '遮': 'shield',
    '蔽': 'hide',
    '掩': 'conceal',
    '蒙': 'cover',
    '盖': 'cover',
    '覆': 'overturn',
    '翻': 'flip',
    '倾': 'tilt',
    '斜': 'slant',
    '侧': 'side',
    '偏': 'biased',
    '歪': 'askew',
    '邪': 'evil',
    '魔': 'demon',
    '鬼': 'ghost',
    '怪': 'strange',
    '异': 'different',
    '殊': 'special',
    '独': 'alone',
    '孤': 'lonely',
    '寡': 'few',
    '稀': 'scarce',
    '罕': 'rare',
    '珍': 'precious',
    '贵': 'expensive',
    '昂': 'high',
    '贱': 'cheap',
    '廉': 'low-cost',
    '低': 'low',
    '劣': 'inferior',
}

def translate_prompt(prompt):
    """Translate Chinese characters in a prompt to English"""
    result = prompt
    # Apply translations
    for chinese, english in char_translations.items():
        if english:  # Only replace if we have a translation
            result = result.replace(chinese, english)
    return result

def count_chinese_chars(text):
    """Count Chinese characters in text"""
    return len(re.findall(r'[\u4e00-\u9fff]', text))

# Load the JSON file
print("Loading image_prompt.json...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

# Process prompts
print("\nTranslating with targeted character mappings...")
translated_count = 0
total_before = 0
total_after = 0

for category in json_data.get('data', []):
    for image_item in category.get('images', []):
        if 'prompt' in image_item:
            original = image_item['prompt']
            chinese_before = count_chinese_chars(original)
            total_before += chinese_before
            
            if chinese_before > 0:
                translated = translate_prompt(original)
                chinese_after = count_chinese_chars(translated)
                total_after += chinese_after
                
                if chinese_after < chinese_before:
                    image_item['prompt'] = translated
                    translated_count += 1

print(f"\nSaving updated file...")
with open('frontend/delightful-web/src/opensource/pages/chatNew/components/AiImageStartPage/image_prompt.json', 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f"\n✅ Translation complete!")
print(f"Modified {translated_count} prompts")
print(f"Chinese characters: {total_before} → {total_after}")
if total_before > 0:
    print(f"Removed: {total_before - total_after} characters ({((total_before - total_after) / total_before * 100):.1f}%)")
