export const v0Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-674eb122a16cc4-83940271",
	debug: false,
	name: "KnowledgeSearch",
	description: "",
	node_type: 52,
	meta: [],
	params: {
		filter_type: "all",
		filters: [],
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-674eb122a16f1",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root node",
				description: "",
				required: [],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					vector_databases: {
						type: "array",
						key: "vector_databases",
						sort: 0,
						title: "Vector Database List",
						description: "desc",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "vector_databases",
							sort: 0,
							title: "Vector Database",
							description: "desc",
							required: ["id", "name"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								id: {
									type: "string",
									key: "id",
									sort: 0,
									title: "Vector Database ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								name: {
									type: "string",
									key: "name",
									sort: 1,
									title: "Vector Database Name",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}





