import i18next from "i18next"

export const v0Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-674c2a7157e4e7-30880767",
	debug: false,
	name: "ExcelLoader",
	description: "",
	node_type: 51,
	meta: [],
	params: {
		files: {
			id: "component-674c2a7157e6b",
			version: "1",
			type: "form",
			structure: {
				type: "array",
				key: "root",
				sort: 0,
				title: i18next.t("common.fileList", { ns: "flow" }),
				description: "",
				required: null,
				value: null,
				encryption: false,
				encryption_value: null,
				items: {
					type: "object",
					key: "file",
					sort: 0,
					title: i18next.t("common.file", { ns: "flow" }),
					description: "",
					required: ["file_name", "file_url"],
					value: null,
					encryption: false,
					encryption_value: null,
					items: null,
					properties: {
						file_name: {
							type: "string",
							key: "file_name",
							sort: 0,
							title: i18next.t("common.fileName", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						file_url: {
							type: "string",
							key: "file_url",
							sort: 1,
							title: i18next.t("common.fileUrl", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				properties: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-674c2a7157f01",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root node",
				description: "",
				required: ["files_spreadsheet"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					files_spreadsheet: {
						type: "array",
						key: "files_spreadsheet",
						sort: 0,
						title: "Spreadsheet Files",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "files_spreadsheet",
							sort: 0,
							title: "File",
							description: "",
							required: ["file_name", "file_url", "file_extension", "sheet"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								file_name: {
									type: "string",
									key: "file_name",
									sort: 0,
									title: "File Name",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_url: {
									type: "string",
									key: "file_url",
									sort: 1,
									title: "File URL",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_extension: {
									type: "string",
									key: "file_extension",
									sort: 2,
									title: "File Extension",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								sheets: {
									type: "array",
									key: "sheets",
									sort: 3,
									title: "Sheets",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: {
										type: "object",
										key: "",
										sort: 0,
										title: "Sheet",
										description: "",
										required: [],
										value: null,
										encryption: false,
										encryption_value: null,
										items: null,
										properties: {
											sheet_name: {
												type: "string",
												key: "sheet_name",
												sort: 0,
												title: "Sheet Name",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											rows: {
												type: "array",
												key: "rows",
												sort: 1,
												title: "Rows",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: {
													type: "object",
													key: "",
													sort: 0,
													title: "Row",
													description: "",
													required: [],
													value: null,
													encryption: false,
													encryption_value: null,
													items: null,
													properties: {
														cells: {
															type: "array",
															key: "cells",
															sort: 0,
															title: "Cells",
															description: "",
															required: null,
															value: null,
															encryption: false,
															encryption_value: null,
															items: {
																type: "object",
																key: "",
																sort: 0,
																title: "Column",
																description: "",
																required: [],
																value: null,
																encryption: false,
																encryption_value: null,
																items: null,
																properties: {
																	value: {
																		type: "string",
																		key: "value",
																		sort: 0,
																		title: "Value",
																		description: "",
																		required: null,
																		value: null,
																		encryption: false,
																		encryption_value: null,
																		items: null,
																		properties: null,
																	},
																	column_index: {
																		type: "string",
																		key: "column_index",
																		sort: 1,
																		title: "Column Index",
																		description: "",
																		required: null,
																		value: null,
																		encryption: false,
																		encryption_value: null,
																		items: null,
																		properties: null,
																	},
																},
															},
															properties: null,
														},
														row_index: {
															type: "string",
															key: "row_index",
															sort: 1,
															title: "Row Index",
															description: "",
															required: null,
															value: null,
															encryption: false,
															encryption_value: null,
															items: null,
															properties: null,
														},
													},
												},
												properties: null,
											},
										},
									},
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
