name: 🐛 Bug Report
description: I've encountered a BUG or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the following form.

        **Before submitting a bug report, you may**
        - Check if the issue has already been reported in [existing issues](https://github.com/saashqdev/delightful/magic/issues), you may find a way to fix it
        - Read our [documentation](https://docs.bedelightful.ai/en), there are some FAQs
        - Try reproducing the issue with the latest version, maybe the bug you've encountered have already been fixed

  - type: dropdown
    id: deployment-type
    attributes:
      label: Deployment Type
      description: How do you run Delightful?
      options:
        - Self-hosted (Docker)
        - Self-hosted (Source)
        - International Site (https://www.bedelightful.ai)
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        What I want and what I've got
      placeholder: |
        For example: I want to log in after installed (what I'm expecting), but it failed with error 404 (what I've got)
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Detailed steps to reproduce the behavior
        Please tell us your environment here
      placeholder: |
        For example:
        On my macbookPro M4, macOS 16.0 (the environment)
        1. Start the service
        2. Goto page xxx
        3. Click xxx
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Logs and Additional Context
      description: |
        Logs and Add any other contexts
      placeholder: |
        If you want to put log here, remember to wrap it with ```, or your log will be a mess

        ```
        2025-01-01 DEBUG just like this
        2025-01-01 DEBUG add a line contains only ``` before and after the logs
        ```

        Other contexts, for example:
        When I use another macbook running macOS 15, it works well
    validations:
      required: false
