import i18next from "i18next"

export const v1Template = {
	node_id: "MAGIC-FLOW-NODE-676d7642c07861-90242876",
	debug: false,
	name: "文档解析",
	description: "",
	node_type: 8,
	node_version: "v1",
	meta: [],
	params: {
		files: {
			id: "component-676d7642c07af",
			version: "1",
			type: "form",
			structure: {
				type: "array",
				key: "root",
				sort: 0,
				title: i18next.t("common.fileList", { ns: "flow" }),
				description: "",
				required: null,
				value: null,
				encryption: false,
				encryption_value: null,
				items: {
					type: "object",
					key: "file",
					sort: 0,
					title: i18next.t("common.file", { ns: "flow" }),
					description: "",
					required: ["file_name", "file_url"],
					value: null,
					encryption: false,
					encryption_value: null,
					items: null,
					properties: {
						file_name: {
							type: "string",
							key: "file_name",
							sort: 0,
							title: i18next.t("common.fileName", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						file_url: {
							type: "string",
							key: "file_url",
							sort: 1,
							title: i18next.t("common.fileUrl", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				properties: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-676d7642c0812",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root节点",
				description: "",
				required: ["content", "files_content"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					content: {
						type: "string",
						key: "content",
						sort: 0,
						title: "全部内容",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					files: {
						type: "array",
						key: "files",
						sort: 1,
						title: "文件",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "file",
							sort: 0,
							title: "文件",
							description: "",
							required: ["name", "url", "extension", "content"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								name: {
									type: "string",
									key: "name",
									sort: 0,
									title: "文件名称",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								url: {
									type: "string",
									key: "url",
									sort: 1,
									title: "文件地址",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								extension: {
									type: "string",
									key: "extension",
									sort: 2,
									title: "文件扩展名",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								content: {
									type: "string",
									key: "content",
									sort: 3,
									title: "内容",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
