/* eslint-disable @typescript-eslint/no-shadow */
/* eslint-disable @typescript-eslint/naming-convention */
import { IconArrowLeftFromArc, IconTimeline } from "@tabler/icons-react"
import React from "react"

export enum customNodeType {
	// Start
	Start = "1",
	// LLM
	LLM = "2",
	// Reply Message
	ReplyMessage = "3",
	// Selector
	If = "4",
	// Code
	Code = "5",
	// Vector
	Vector = "6",
	// Magic Table
	Table = "7",
	// Loader
	Loader = "8",
	// Variable
	Variable = "9",
	// HTTP Request
	HTTP = "10",
	// Sub-process
	Sub = "11",
	// End
	End = "12",
	// Knowledge Retrieval
	Knowledge = "13",
	// Intent Recognition
	IntentionRecognition = "14",
	// Tools
	Tools = "15",
	// Variable Save
	VariableSave = "21",
	// Loop
	Loop = "30",
	// Loop Body
	LoopBody = "31",
	// Loop End
	LoopEnd = "32",
	// Search Users
	SearchUsers = "28",
	// Agent Node
	Agent = "29",
}

export const templateMap = {
	[customNodeType.Start]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-663c385e5a83f4-29733783",
			name: "Start",
			description: "",
			node_type: 1,
			meta: [],
			params: {
				branches: [
					{
						trigger_type: 1,
						next_nodes: [],
						branch_id: "1",
						config: null,
						input: {
							widget: null,
							form: {
								id: "component-663c385e5b541",
								version: "1",
								type: "form",
								structure: {
									type: "object",
									key: "root",
									sort: 0,
								title: "root node",
									description: "",
									required: ["nickname", "chat_time", "message_type", "content"],
									value: null,
									items: null,
									properties: {
										nickname: {
											type: "string",
											key: "nickname",
											sort: 0,
										title: "User Nickname",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										chat_time: {
											type: "string",
											key: "chat_time",
											sort: 1,
										title: "Send Time",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										message_type: {
											type: "string",
											key: "message_type",
											sort: 2,
										title: "Message Type",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										content: {
											type: "string",
											key: "content",
											sort: 3,
										title: "Message Content",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
									},
								},
							},
						},
						output: {
							widget: null,
							form: {
								id: "component-663c385e5b541",
								version: "1",
								type: "form",
								structure: {
									type: "object",
									key: "root",
									sort: 0,
									title: "rootnode",
									description: "",
									required: ["nickname", "chat_time", "message_type", "content"],
									value: null,
									items: null,
									properties: {
										nickname: {
											type: "string",
											key: "nickname",
											sort: 0,
										title: "User Nickname",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										chat_time: {
											type: "string",
											key: "chat_time",
											sort: 1,
										title: "Send Time",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										message_type: {
											type: "string",
											key: "message_type",
											sort: 2,
										title: "Message Type",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										content: {
											type: "string",
											key: "content",
											sort: 3,
										title: "Message Content",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
									},
								},
							},
						},
					},
					{
						trigger_type: 2,
						next_nodes: [],
						branch_id: "2",
						config: null,
						input: {
							widget: null,
							form: {
								id: "component-663c385e5b7f1",
								version: "1",
								type: "form",
								structure: {
									type: "object",
									key: "root",
									sort: 0,
									title: "rootnode",
									description: "",
									required: ["nickname", "open_time"],
									value: null,
									items: null,
									properties: {
										nickname: {
											type: "string",
											key: "nickname",
											sort: 0,
										title: "User Nickname",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										open_time: {
											type: "string",
											key: "open_time",
											sort: 1,
										title: "Open Time",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
									},
								},
							},
						},
						output: {
							widget: null,
							form: {
								id: "component-663c385e5b7f1",
								version: "1",
								type: "form",
								structure: {
									type: "object",
									key: "root",
									sort: 0,
									title: "rootnode",
									description: "",
									required: ["nickname", "open_time"],
									value: null,
									items: null,
									properties: {
										nickname: {
											type: "string",
											key: "nickname",
											sort: 0,
											title: "User Nickname",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
										open_time: {
											type: "string",
											key: "open_time",
											sort: 1,
											title: "Open Time",
											description: "",
											required: null,
											value: null,
											items: null,
											properties: null,
										},
									},
								},
							},
						},
					},
				],
			},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.If]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-66c444c8ca1934-29144044",
		name: "Conditional Judgment",
			description: "",
			node_type: 4,
			meta: [],
			params: {
				max_execute_num: 1,
				branches: [
					{
						branch_id: "branch_66c444c8ca355",
						branch_type: "if",
						next_nodes: [],
						parameters: {
							id: "component-66c444c8ca73e",
							version: "1",
							type: "condition",
							structure: null,
						},
					},
					{
						branch_id: "branch_66c444c8ca7d5",
						branch_type: "else",
						next_nodes: [],
						parameters: null,
					},
				],
			},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.Sub]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-6649da5637d546-69160385",
			name: "subprocess",
			description: "",
			node_type: 11,
			meta: [],
			params: {
				sub_flow_id: "DELIGHTFUL-FLOW-6629fe3e606e03-15176825",
			},
			next_nodes: [],
			input: {
				widget: null,
				form: {
					id: "component-662617c1a0884",
					version: "1",
					type: "form",
					structure: {
						type: "object",
						key: "root",
						sort: 0,
						title: null,
						description: null,
						required: ["input"],
						value: null,
						items: null,
						properties: {
							input: {
								type: "string",
								key: "input",
								sort: 0,
								title: "Input",
								description: "",
								required: null,
								value: null,
								items: null,
								properties: null,
							},
						},
					},
				},
			},
			output: {
				widget: null,
				form: {
					id: "component-662617a69868d",
					version: "1",
					type: "form",
					structure: {
						type: "object",
						key: "root",
						sort: 0,
						title: null,
						description: null,
						required: [],
						value: null,
						items: null,
						properties: {
							output: {
								type: "string",
								key: "output",
								sort: 0,
								title: "Output",
								description: "",
								required: null,
								value: {
									type: "expression",
									const_value: null,
									expression_value: [
										{
											type: "fields",
											value: "DELIGHTFUL-FLOW-NODE-6629f9ee4d6248-06936049.output",
											name: "output",
											args: null,
										},
									],
								},
								items: null,
								properties: null,
							},
						},
					},
				},
			},
		},

		v1: {
			node_id: "DELIGHTFUL-FLOW-NODE-6649da5637d546-69160385",
			name: "subprocessversion2",
			description: "",
			node_type: 11,
			meta: [],
			params: {
				sub_flow_id: "DELIGHTFUL-FLOW-6629fe3e606e03-15176825",
			},
			next_nodes: [],
			input: {
				widget: null,
				form: {
					id: "component-662617c1a0884",
					version: "1",
					type: "form",
					structure: {
						type: "object",
						key: "root",
						sort: 0,
						title: null,
						description: null,
						required: ["input"],
						value: null,
						items: null,
						properties: {
							input: {
								type: "string",
								key: "input",
								sort: 0,
								title: "Input",
								description: "",
								required: null,
								value: null,
								items: null,
								properties: null,
							},
						},
					},
				},
			},
			output: {
				widget: null,
				form: {
					id: "component-662617a69868d",
					version: "1",
					type: "form",
					structure: {
						type: "object",
						key: "root",
						sort: 0,
						title: null,
						description: null,
						required: [],
						value: null,
						items: null,
						properties: {
							output_v2: {
								type: "number",
								key: "output",
								sort: 0,
							title: "Output",
								description: "",
								required: null,
								value: {
									type: "expression",
									const_value: null,
									expression_value: [
										{
											type: "fields",
											value: "DELIGHTFUL-FLOW-NODE-6629f9ee4d6248-06936049.output",
											name: "output",
											args: null,
										},
									],
								},
								items: null,
								properties: null,
							},
						},
					},
				},
			},
		},
	},

	[customNodeType.Loop]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-66a70a8da8ed48-26322039",
			name: "loop",
			description: "",
			node_type: 22,
			meta: [],
			params: {
				type: "array", // Count type: count, loop array: array, conditional loop: condition,
				condition: {
					// Enabled for conditional loop, used to provide a loop termination condition
					id: "component-66da72180d2e1",
					version: "1",
					type: "condition",
					structure: undefined,
				},
				count: {
					// Enabled for count loop
					id: "component-66da73d27fea0",
					version: "1",
					type: "value",
					structure: null,
				},
				array: {
					// Enabled when looping through array
					id: "component-66da73d27fea0",
					version: "1",
					type: "value",
					structure: null,
				},
				max_loop_count: {
					// Maximum loop count limit, enabled for conditional loops, can be empty
					id: "component-66da73d27fea0",
					version: "1",
					type: "value",
					structure: null,
				},
			},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.LoopEnd]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-66a70a8da8ed48-2632203d",
			name: "Loop Termination",
			description: "",
			node_type: 24,
			meta: [],
			params: {},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.LoopBody]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-66a70a8da8ed48-2632203f",
			name: "Loop Body",
			description: "",
			node_type: 23,
			meta: [],
			params: {},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.VariableSave]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-66a2a8453cfd12-52796719",
			name: "Variable Settings",
			description: "",
			node_type: 21,
			meta: [],
			params: {
				variables: {
					form: {
						id: "component-66a2a8453cfe4",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "rootnode",
							description: null,
							required: ["variable_name", "variable_type"],
							value: null,
							items: null,
							properties: {
								variable_name: {
									type: "string",
									key: "variable_name",
									sort: 0,
									title: "Variable Name",
									description: "",
									required: null,
									value: null,
									items: null,
									properties: null,
								},
								variable_type: {
									type: "string",
									key: "variable_type",
									sort: 1,
									title: "Variable Type",
									description: "",
									required: null,
									value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
					page: null,
				},
			},
			next_nodes: [],
			input: null,
			output: null,
		},
	},
	[customNodeType.LLM]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-6753cb5235e676-30935789",
			debug: false,
			name: "LLM Chat",
			description: "",
			node_type: 2,
			meta: [],
			params: {
				model: "gpt-4o-global",
				system_prompt: {
					id: "component-6753cb5235e78",
					version: "1",
					type: "value",
					structure: {
						type: "expression",
						const_value: null,
						expression_value: null,
					},
				},
				user_prompt: {
					id: "component-6753cb5235ea2",
					version: "1",
					type: "value",
					structure: {
						type: "expression",
						const_value: null,
						expression_value: null,
					},
				},
				model_config: {
					auto_memory: true,
					max_record: 50,
					temperature: 0.5,
				},
				tools: [],
				option_tools: [],
				knowledge_config: {
					operator: "developer",
					knowledge_list: [
						{
							knowledge_code: "",
							knowledge_type: 2,
							business_id: "",
							name: "",
							description: "",
						},
					],
					limit: 5,
					score: 0.4,
				},
				messages: {
					id: "component-6753cb5235ec6",
					version: "1",
					type: "form",
					structure: {
						type: "array",
						key: "root",
						sort: 0,
						title: "historical message",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "messages",
							sort: 0,
							title: "historical message",
							description: "",
							required: ["role", "content"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								role: {
									type: "string",
									key: "role",
									sort: 0,
									title: "role",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								content: {
									type: "string",
									key: "content",
									sort: 1,
								title: "Content",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
			next_nodes: [],
			input: null,
			output: {
				widget: null,
				form: {
					id: "component-6753cb5235f3e",
					version: "1",
					type: "form",
					structure: {
						type: "object",
						key: "root",
						sort: 0,
						title: "rootnode",
						description: "",
						required: ["text", "use_tools"],
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: {
							use_tools: {
								type: "array",
								key: "use_tools",
								sort: 0,
								title: "Tools Used",
								description: "",
								required: null,
								value: null,
								encryption: false,
								encryption_value: null,
								items: {
									type: "object",
									key: "",
									sort: 0,
									title: "Tool Details",
									description: "",
									required: [],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										tool_name: {
											type: "string",
											key: "tool_name",
											sort: 0,
											title: "Tool Name",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										success: {
											type: "boolean",
											key: "success",
											sort: 1,
											title: "Is Successful",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										error_message: {
											type: "string",
											key: "error_message",
											sort: 2,
											title: "Error Information",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										arguments: {
											type: "object",
											key: "arguments",
											sort: 3,
											title: "Tool Parameters",
											description: "",
											required: [],
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										call_result: {
											type: "string",
											key: "call_result",
											sort: 4,
											title: "Call Result",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										elapsed_time: {
											type: "string",
											key: "elapsed_time",
											sort: 5,
											title: "Elapsed Time",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
									},
								},
								properties: null,
							},
							text: {
								type: "string",
								key: "text",
								sort: 1,
								title: "LLM Response Text",
								description: "",
								required: null,
								value: null,
								encryption: false,
								encryption_value: null,
								items: null,
								properties: null,
							},
						},
					},
				},
			},
			system_output: null,
		},
	},
	[customNodeType.Tools]: {
		v0: {
			node_id: "DELIGHTFUL-FLOW-NODE-674c4f70bc3966-92064256",
			debug: false,
			name: "tool",
			description: "",
			node_type: 26,
			meta: [],
			params: {
				tool_id: "",
				mode: "llm",
				custom_system_input: {
					widget: null,
					form: {
						id: "component-674c4f70bc3a8",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				async: false,
				model: "gpt-4o-global",
				model_config: {
					auto_memory: false,
					max_record: 50,
					temperature: 0.5,
				},
				user_prompt: {
					id: "component-674c4f70bc485",
					version: "1",
					type: "value",
					structure: {
						type: "expression",
						const_value: null,
						expression_value: null,
					},
				},
			},
			next_nodes: [],
			input: {
				widget: null,
				form: null,
			},
			output: null,
			system_output: null,
		},
	},
}

function addVersionKeyToNodes(nodes: Record<string, any>): Record<string, any> {
	return Object.fromEntries(Object.entries(nodes).map(([key, value]) => [key, { v0: value }]))
}

export const nodeSchemaMap = {
	[customNodeType.Start]: {
		schema: {
			label: "startnode",
			icon: <IconArrowLeftFromArc color="#fff" stroke={2} size={18} />,
			color: "#315CEC",
			id: customNodeType.Start,
				desc: "When the following event is triggered, the flow will start execution from this module",
			handle: {
				withSourceHandle: false,
				withTargetHandle: false,
			},
			changeable: {
				nodeType: false,
			},
			style: {
				width: "480px",
			},
			// params: templateMap[customNodeType.Start].params,
			// output: templateMap[customNodeType.Start].output,
		},
		component: () => <div />,
	},

	[customNodeType.Sub]: {
		schema: {
			label: "subprocess",
			icon: <IconTimeline color="#fff" stroke={1} size={18} />,
			color: "#9DC900",
			id: customNodeType.Sub,
				desc: "Partial functionality modules can be assigned to subprocesses for orchestration, avoiding an overly large main flow",
			handle: {
				withSourceHandle: true,
				withTargetHandle: true,
			},
			style: {
				width: "800px",
			},
			// params: templateMap[customNodeType.Sub].params,
			// output: templateMap[customNodeType.Sub].output,
		},
		component: () => <div />,
	},
}

export default nodeSchemaMap

