export const v0Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-676d850ad23642-57271282",
	debug: false,
	name: "Start",
	description: "",
	node_type: 1,
	node_version: "v0",
	meta: [],
	params: {
		branches: [
			{
				branch_id: "branch_676d850ad237f",
				trigger_type: 1,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-676d850ad23aa",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root node",
							description: "",
							required: [
								"user_id",
								"nickname",
								"chat_time",
								"message_type",
								"content",
								"organization_code",
								"conversation_id",
								"topic_id",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								user_id: {
									type: "string",
									key: "user_id",
									sort: 0,
									title: "User ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								nickname: {
									type: "string",
									key: "nickname",
									sort: 1,
									title: "Nickname",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								chat_time: {
									type: "string",
									key: "chat_time",
									sort: 2,
									title: "Sent Time",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_type: {
									type: "string",
									key: "message_type",
									sort: 3,
									title: "Message Type",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_content: {
									type: "string",
									key: "message_content",
									sort: 4,
									title: "Message Content",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								files: {
									type: "array",
									key: "files",
									sort: 5,
									title: "File List",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: {
										type: "object",
										key: "files",
										sort: 0,
										title: "File",
										description: "",
										required: ["file_name", "file_url"],
										value: null,
										encryption: false,
										encryption_value: null,
										items: null,
										properties: {
											file_name: {
												type: "string",
												key: "file_name",
												sort: 0,
												title: "File Name",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_url: {
												type: "string",
												key: "file_url",
												sort: 1,
												title: "File URL",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_ext: {
												type: "string",
												key: "file_ext",
												sort: 2,
												title: "File Extension",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_size: {
												type: "number",
												key: "file_size",
												sort: 3,
												title: "File Size",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
										},
									},
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 6,
									title: "Organization Code",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 7,
									title: "Conversation ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 8,
									title: "Topic ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_676d850ad24bd",
				trigger_type: 2,
				next_nodes: [],
				config: {
					interval: 10,
					unit: "minutes",
				},
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-676d850ad24d0",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root node",
							description: "",
							required: [
								"user_id",
								"nickname",
								"open_time",
								"organization_code",
								"conversation_id",
								"topic_id",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								user_id: {
									type: "string",
									key: "user_id",
									sort: 0,
									title: "User ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								nickname: {
									type: "string",
									key: "nickname",
									sort: 1,
									title: "Nickname",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								open_time: {
									type: "string",
									key: "open_time",
									sort: 2,
									title: "Open Time",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 3,
									title: "Organization Code",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 4,
									title: "Conversation ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 5,
									title: "Topic ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_676d850ad2533",
				trigger_type: 4,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-676d850ad2536",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				system_output: {
					widget: null,
					form: {
						id: "component-676d850ad2574",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root node",
							description: "",
							required: [
								"user_id",
								"nickname",
								"chat_time",
								"message_type",
								"content",
								"organization_code",
								"conversation_id",
								"topic_id",
							],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								user_id: {
									type: "string",
									key: "user_id",
									sort: 0,
									title: "User ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								nickname: {
									type: "string",
									key: "nickname",
									sort: 1,
									title: "Nickname",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								chat_time: {
									type: "string",
									key: "chat_time",
									sort: 2,
									title: "Sent Time",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_type: {
									type: "string",
									key: "message_type",
									sort: 3,
									title: "Message Type",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								message_content: {
									type: "string",
									key: "message_content",
									sort: 4,
									title: "Message Content",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								files: {
									type: "array",
									key: "files",
									sort: 5,
									title: "File List",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: {
										type: "object",
										key: "files",
										sort: 0,
										title: "File",
										description: "",
										required: ["file_name", "file_url"],
										value: null,
										encryption: false,
										encryption_value: null,
										items: null,
										properties: {
											file_name: {
												type: "string",
												key: "file_name",
												sort: 0,
												title: "File Name",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_url: {
												type: "string",
												key: "file_url",
												sort: 1,
												title: "File URL",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_ext: {
												type: "string",
												key: "file_ext",
												sort: 2,
												title: "File Extension",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
											file_size: {
												type: "number",
												key: "file_size",
												sort: 3,
												title: "File Size",
												description: "",
												required: null,
												value: null,
												encryption: false,
												encryption_value: null,
												items: null,
												properties: null,
											},
										},
									},
									properties: null,
								},
								organization_code: {
									type: "string",
									key: "organization_code",
									sort: 6,
									title: "Organization Code",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								conversation_id: {
									type: "string",
									key: "conversation_id",
									sort: 7,
									title: "Conversation ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								topic_id: {
									type: "string",
									key: "topic_id",
									sort: 8,
									title: "Topic ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				custom_system_output: {
					widget: null,
					form: {
						id: "component-676d850ad2646",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
			},
			{
				branch_id: "branch_676d850ad2659",
				trigger_type: 5,
				next_nodes: [],
				config: null,
				input: null,
				output: null,
				system_output: null,
				custom_system_output: null,
			},
			{
				branch_id: "branch_676d850ad265c",
				trigger_type: 7,
				next_nodes: [],
				config: null,
				input: null,
				output: {
					widget: null,
					form: {
						id: "component-676d850ad266b",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: "root node",
							description: "",
							required: ["add_time", "user"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								user: {
									type: "object",
									key: "user",
									sort: 0,
									title: "User",
									description: "",
									required: ["id", "nickname", "real_name"],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: {
										id: {
											type: "string",
											key: "id",
											sort: 0,
											title: "User ID",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										nickname: {
											type: "string",
											key: "nickname",
											sort: 1,
											title: "Nickname",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
										real_name: {
											type: "string",
											key: "real_name",
											sort: 2,
											title: "Real Name",
											description: "",
											required: null,
											value: null,
											encryption: false,
											encryption_value: null,
											items: null,
											properties: null,
										},
									},
								},
								add_time: {
									type: "string",
									key: "add_time",
									sort: 1,
									title: "Added Time",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
					},
				},
				system_output: null,
				custom_system_output: null,
			},
		],
	},
	next_nodes: [],
	input: null,
	output: null,
	system_output: null,
}
