import i18next from "i18next"

export const v1Template = {
	node_id: "MAGIC-FLOW-NODE-677633dfaf2e16-08254921",
	debug: false,
	name: "大模型调用",
	description: "",
	node_type: 2,
	node_version: "v1",
	meta: [],
	params: {
		model: "",
		system_prompt: {
			id: "component-677633dfaf2fc",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		user_prompt: {
			id: "component-677633dfaf31e",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		model_config: {
			auto_memory: true,
			max_record: 50,
			temperature: 0.5,
			vision: true,
			vision_model: "",
		},
		tools: [],
		option_tools: [],
		knowledge_config: {
			operator: "developer",
			knowledge_list: [],
			limit: 5,
			score: 0.4,
		},
		messages: {
			id: "component-677633dfaf338",
			version: "1",
			type: "form",
			structure: {
				type: "array",
				key: "root",
				sort: 0,
				title: i18next.t("common.historyMessages", { ns: "flow" }),
				description: "",
				required: null,
				value: null,
				encryption: false,
				encryption_value: null,
				items: {
					type: "object",
					key: "messages",
					sort: 0,
					title: i18next.t("common.historyMessages", { ns: "flow" }),
					description: "",
					required: ["role", "content"],
					value: null,
					encryption: false,
					encryption_value: null,
					items: null,
					properties: {
						role: {
							type: "string",
							key: "role",
							sort: 0,
							title: i18next.t("common.role", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						content: {
							type: "string",
							key: "content",
							sort: 1,
							title: i18next.t("common.content", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				properties: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-677633dfaf392",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root节点",
				description: "",
				required: ["response", "tool_calls"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					response: {
						type: "string",
						key: "response",
						sort: 0,
						title: "大模型响应",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					tool_calls: {
						type: "array",
						key: "tool_calls",
						sort: 1,
						title: "调用过的工具",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "",
							sort: 0,
							title: "调用过的工具",
							description: "",
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								name: {
									type: "string",
									key: "name",
									sort: 0,
									title: "工具名称",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								success: {
									type: "boolean",
									key: "success",
									sort: 1,
									title: "是否成功",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								error_message: {
									type: "string",
									key: "error_message",
									sort: 2,
									title: "错误信息",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								arguments: {
									type: "object",
									key: "arguments",
									sort: 3,
									title: "工具参数",
									description: "",
									required: [],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								call_result: {
									type: "string",
									key: "call_result",
									sort: 4,
									title: "调用结果",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								elapsed_time: {
									type: "string",
									key: "elapsed_time",
									sort: 5,
									title: "耗时",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
