export const v1Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-67739d5e267530-42312057",
	debug: false,
	name: "Persistent Database / Data Load",
	description: "",
	node_type: 19,
	node_version: "v1",
	meta: [],
	params: {
		cache_scope: "topic",
		cache_key: {
			id: "component-67739d5e26771",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-67739d5e2679c",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "Root Node",
				description: "",
				required: ["value"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					value: {
						type: "string",
						key: "value",
						sort: 0,
						title: "Data Value",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
