export const v0Template = {
	node_id: "MAGIC-FLOW-NODE-674ebb9acdec14-22731690",
	debug: false,
	name: "知识匹配",
	description: "",
	node_type: 17,
	meta: [],
	params: {
		knowledge_codes: [],
		vector_database_ids: {
			id: "component-674ebb9acded1",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		query: {
			id: "component-674ebb9acdeeb",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		metadata_filter: {
			id: "component-674ebb9acdef5",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: [],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: null,
			},
		},
		limit: 5,
		score: 0.4,
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-674ebb9acdf21",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root节点",
				description: "",
				required: ["similarity_contents", "similarity_content"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					similarity_contents: {
						type: "array",
						key: "similarity_contents",
						sort: 0,
						title: "召回的结果集",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "string",
							key: "0",
							sort: 0,
							title: "结果",
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						properties: null,
					},
					similarity_content: {
						type: "string",
						key: "similarity_content",
						sort: 1,
						title: "召回的结果",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					fragments: {
						type: "array",
						key: "fragments",
						sort: 2,
						title: "片段列表",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "fragment",
							sort: 0,
							title: "片段",
							description: "",
							required: ["content"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								business_id: {
									type: "string",
									key: "business_id",
									sort: 0,
									title: "业务 ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								content: {
									type: "string",
									key: "content",
									sort: 1,
									title: "内容",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								metadata: {
									type: "object",
									key: "metadata",
									sort: 2,
									title: "元数据",
									description: "",
									required: [],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
