export const v1Template = {
	node_id: "MAGIC-FLOW-NODE-676d736eca7d69-15945310",
	debug: false,
	name: "HTTP 请求",
	description: "",
	node_type: 10,
	node_version: "v1",
	meta: [],
	params: {
		api: {
			id: "component-676d736eca7f4",
			version: "1",
			type: "api",
			structure: {
				method: "GET",
				domain: "",
				path: "",
				uri: null,
				url: "",
				proxy: "",
				auth: "",
				request: {
					params_query: {
						id: "component-676d736ecaabc",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
					params_path: {
						id: "component-676d736ecaace",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
					body_type: "json",
					body: {
						id: "component-676d736ecab1d",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
					headers: {
						id: "component-676d736ecab23",
						version: "1",
						type: "form",
						structure: {
							type: "object",
							key: "root",
							sort: 0,
							title: null,
							description: null,
							required: [],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-676d736ecab4a",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: [],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: null,
			},
		},
	},
	system_output: {
		widget: null,
		form: {
			id: "component-676d736ecab5a",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: ["body", "status_code"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					body: {
						type: "string",
						key: "body",
						sort: 0,
						title: "响应体",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					status_code: {
						type: "number",
						key: "status_code",
						sort: 1,
						title: "状态码",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
				},
			},
		},
	},
}
