export const v0Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-673edf2100afc7-50651959",
	debug: false,
	name: "Wait for New Message",
	description: "",
	node_type: 29,
	meta: [],
	params: {
		timeout_config: {
			enabled: false,
			interval: 10,
			unit: "minutes",
		},
	},
	next_nodes: [],
	input: {
		widget: null,
		form: {
			id: "component-673edf2100b29",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "Root Node",
				description: "",
				required: ["user_id", "nickname", "chat_time", "message_type", "content"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					user_id: {
						type: "string",
						key: "user_id",
						sort: 0,
						title: "User ID",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					nickname: {
						type: "string",
						key: "nickname",
						sort: 1,
						title: "User Nickname",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					chat_time: {
						type: "string",
						key: "chat_time",
						sort: 2,
						title: "Send Time",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					message_type: {
						type: "string",
						key: "message_type",
						sort: 3,
						title: "Message Type",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					content: {
						type: "string",
						key: "content",
						sort: 4,
						title: "Message Content",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					files: {
						type: "array",
						key: "files",
						sort: 5,
						title: "File List",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "files",
							sort: 0,
							title: "File",
							description: "",
							required: ["file_name", "file_url"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								file_name: {
									type: "string",
									key: "file_name",
									sort: 0,
									title: "File Name",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_url: {
									type: "string",
									key: "file_url",
									sort: 1,
									title: "File URL",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	output: {
		widget: null,
		form: {
			id: "component-673edf2100b29",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "Root Node",
				description: "",
				required: ["user_id", "nickname", "chat_time", "message_type", "content"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					user_id: {
						type: "string",
						key: "user_id",
						sort: 0,
						title: "User ID",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					nickname: {
						type: "string",
						key: "nickname",
						sort: 1,
						title: "User Nickname",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					chat_time: {
						type: "string",
						key: "chat_time",
						sort: 2,
						title: "Send Time",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					message_type: {
						type: "string",
						key: "message_type",
						sort: 3,
						title: "Message Type",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					content: {
						type: "string",
						key: "content",
						sort: 4,
						title: "Message Content",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					files: {
						type: "array",
						key: "files",
						sort: 5,
						title: "File List",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "files",
							sort: 0,
							title: "File",
							description: "",
							required: ["file_name", "file_url"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								file_name: {
									type: "string",
									key: "file_name",
									sort: 0,
									title: "File Name",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_url: {
									type: "string",
									key: "file_url",
									sort: 1,
									title: "File URL",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}






