import i18next from "i18next"

export const v0Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-67483d2676a6d4-83392577",
	debug: false,
	name: "Data Loading",
	description: "",
	node_type: 8,
	meta: [],
	params: {
		files: {
			id: "component-67483d2676a85",
			version: "1",
			type: "form",
			structure: {
				type: "array",
				key: "root",
				sort: 0,
				title: i18next.t("common.fileList", { ns: "flow" }),
				description: "",
				required: null,
				value: null,
				encryption: false,
				encryption_value: null,
				items: {
					type: "object",
					key: "file",
					sort: 0,
					title: i18next.t("common.file", { ns: "flow" }),
					description: "",
					required: ["file_name", "file_url"],
					value: null,
					encryption: false,
					encryption_value: null,
					items: null,
					properties: {
						file_name: {
							type: "string",
							key: "file_name",
							sort: 0,
							title: i18next.t("common.fileName", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						file_url: {
							type: "string",
							key: "file_url",
							sort: 1,
							title: i18next.t("common.fileUrl", { ns: "flow" }),
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
					},
				},
				properties: null,
			},
		},
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-67483d2676aee",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root node",
				description: "",
				required: ["content", "files_content"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					content: {
						type: "string",
						key: "content",
						sort: 0,
						title: "Content",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: null,
						properties: null,
					},
					files_content: {
						type: "array",
						key: "files_content",
						sort: 1,
						title: "File Content",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "file",
							sort: 0,
							title: "File",
							description: "",
							required: ["file_name", "file_url", "file_extension", "content"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								file_name: {
									type: "string",
									key: "file_name",
									sort: 0,
									title: "File Name",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_url: {
									type: "string",
									key: "file_url",
									sort: 1,
									title: "File URL",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								file_extension: {
									type: "string",
									key: "file_extension",
									sort: 2,
									title: "File Extension",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								content: {
									type: "string",
									key: "content",
									sort: 3,
									title: "Content",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
