export const v1Template = {
	node_id: "DELIGHTFUL-FLOW-NODE-676d75ed2a27c6-24690200",
	debug: false,
	name: "Vector Database / Query",
	description: "",
	node_type: 17,
	node_version: "v1",
	meta: [],
	params: {
		knowledge_codes: [],
		vector_database_ids: {
			id: "component-676d75ed2a297",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		query: {
			id: "component-676d75ed2a2b4",
			version: "1",
			type: "value",
			structure: {
				type: "expression",
				const_value: null,
				expression_value: null,
			},
		},
		metadata_filter: {
			id: "component-676d75ed2a2be",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: null,
				description: null,
				required: [],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: null,
			},
		},
		limit: 5,
		score: 0.4,
	},
	next_nodes: [],
	input: null,
	output: {
		widget: null,
		form: {
			id: "component-676d75ed2a2e5",
			version: "1",
			type: "form",
			structure: {
				type: "object",
				key: "root",
				sort: 0,
				title: "root node",
				description: "",
				required: ["similarities"],
				value: null,
				encryption: false,
				encryption_value: null,
				items: null,
				properties: {
					similarities: {
						type: "array",
						key: "similarities",
						sort: 0,
						title: "Recalled Result Set",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "string",
							key: "0",
							sort: 0,
							title: "Result",
							description: "",
							required: null,
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: null,
						},
						properties: null,
					},
					fragments: {
						type: "array",
						key: "fragments",
						sort: 1,
						title: "Fragment List",
						description: "",
						required: null,
						value: null,
						encryption: false,
						encryption_value: null,
						items: {
							type: "object",
							key: "fragment",
							sort: 0,
							title: "Fragment",
							description: "",
							required: ["content"],
							value: null,
							encryption: false,
							encryption_value: null,
							items: null,
							properties: {
								business_id: {
									type: "string",
									key: "business_id",
									sort: 0,
									title: "Business ID",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								content: {
									type: "string",
									key: "content",
									sort: 1,
									title: "Content",
									description: "",
									required: null,
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
								metadata: {
									type: "object",
									key: "metadata",
									sort: 2,
									title: "Metadata",
									description: "",
									required: [],
									value: null,
									encryption: false,
									encryption_value: null,
									items: null,
									properties: null,
								},
							},
						},
						properties: null,
					},
				},
			},
		},
	},
	system_output: null,
}
